---
- hosts: managesf
  gather_facts: no
  tasks:
  - include: tasks/fetchupstream.yml
  - include: tasks/stopsfservices.yml
  - include: tasks/fix_redmine.yml
  - include: tasks/edeploysync.yml
  - include: tasks/gnocchi.yml
  - include: tasks/SFServiceUser.yml
