---
- hosts: managesf
  tasks:
  - name: systemctl daemon-reload
    shell: systemctl daemon-reload
  - name: Restart the configuration script
    shell: sfconfig.sh > /var/log/upgrade-bootstrap.log
  - name: Restart grafana-server
    shell: systemctl restart grafana-server
  - name: migrate data from sqlite to mariadb
    shell: /usr/local/bin/migrate_sqlite_to_mariadb.py
- hosts: jenkins
  gather_facts: no
  tasks:
  - include: tasks/submitconfigreview.yml
- hosts: gerrit
  gather_facts: no
  tasks:
  - include: tasks/allprojectsupdate.yml
  - include: tasks/schemaupdate.yml
