---
- hosts: managesf
  gather_facts: no
  tasks:
  - include: tasks/fetchupstream.yml
  - include: tasks/stopsfservices.yml
  - include: tasks/edeploysync.yml
  - shell: /usr/local/bin/sf-update-uid-gid.py 2>&1 | tee -a /var/log/sf_ids_update.log
  # gnocchi
  - include: tasks/new_creds.yml sf_secret_name=grafana_sql_pwd
  - include: tasks/new_creds.yml sf_secret_name=gnocchi_sql_pwd
  # SFService user
  - include: tasks/new_creds.yml sf_secret_name=service_user_pwd
  # Etherpad
  - include: tasks/new_creds.yml sf_secret_name=etherpad_admin_key
