---
- hosts: managesf
  gather_facts: no
  tasks:
  - include: tasks/fetchupstream.yml
  - include: tasks/SFServiceUser.yml
- hosts: instances
  gather_facts: no
  tasks:
  - include: tasks/fetchupstream.yml
  - include: tasks/stopsfservices.yml
  - include: tasks/edeploysync.yml
  - include: tasks/graphite.yml
