---
- hosts: elasticsearch
  tasks:
  # repoXplorer does not manage DB version so wipe it
  - name: Remove repoxplorer EL index
    command: curl -XDELETE "http://elasticsearch:9200/repoxplorer/"

- hosts: repoxplorer
  tasks:
  - name: "Restart repoxplorer indexer"
    service: name=repoxplorer state=restarted
