---
- hosts: install-server
  pre_tasks:
  - include: tasks/remove_puppet.yaml
  tasks:
  - include: tasks/fetchupstream.yml
  - include: tasks/gerritbot_configrepo_import.yml
  - include: tasks/gerrit_configrepo_import.yml
  - include: tasks/zuul_layout_namechange.yml
  - include: tasks/sf_jjb_namechange.yml
  - include: tasks/policy_configrepo.yml
  - include: tasks/resources_configrepo.yml
  - include: tasks/gerrit_default_jenkins_user.yml

- hosts: all
  tasks:
  - include: tasks/clean_root_crontab.yml
  - include: tasks/stopsfservices.yml

- hosts: all
  tasks:
  - name: Synchronize FS with eDeploy
    command: edeploy upgrade {{ version }}
