---
- hosts: all
  tasks:
  - include: tasks/bootloader.yml
  - shell: /usr/local/bin/sf-update-uid-gid.py 2>&1 | tee -a /var/log/sf_ids_update.log

- hosts: install-server
  tasks:
  # storyboard
  - include: tasks/new_creds.yml sf_secret_name=storyboard_sql_pwd
  - include: tasks/new_creds.yml sf_secret_name=storyboard_service_token
  # SFService user
  - include: tasks/new_creds.yml sf_secret_name=service_user_pwd
  # Etherpad
  - include: tasks/new_creds.yml sf_secret_name=etherpad_admin_key
  # Cauth and managesf database access
  - include: tasks/new_creds.yml sf_secret_name=cauth_sql_pwd
  - include: tasks/new_creds.yml sf_secret_name=managesf_sql_pwd
  # 2.0.0: Remove hosts.yaml hiera
  - file: path=/etc/software-factory/hosts.yaml state=absent
  # 2.3.0: Remove gerrit.yaml hiera
  - stat: path=/etc/software-factory/gerrit.yaml
    register: gerrit_hiera
  - command: awk '/gerrit_heap_limit/ { print $2 }' /etc/software-factory/gerrit.yaml
    register: heap_limit
    when: gerrit_hiera.stat.exists == True
  - command: hieraedit.py --yaml /etc/software-factory/custom-vars.yaml gerrit_heap_limit {{ heap_limit.stdout }}
    when: gerrit_hiera.stat.exists == True
  - file: path=/etc/software-factory/gerrit.yaml state=absent

- hosts: managesf
  tasks:
  # 2.2.7: managesf is running with its own user
  - name: Make sure /var/log/managesf is owned by managesf
    command: chown -R 949:949 /var/log/managesf

- hosts: all
  tasks:
  - name: systemctl daemon-reload
    shell: systemctl daemon-reload

- hosts: jenkins
  tasks:
  - name: Be sure Jenkins master executors amount is 1
    replace: dest=/var/lib/jenkins/config.xml regexp='<numExecutors>.*</numExecutors>' replace='<numExecutors>1</numExecutors>'

- hosts: install-server
  tasks:
  # /var/log/software-factory only exists after 2.2.7
  - name: Make sure /var/log/software-factory exists
    file: path=/var/log/software-factory state=directory mode=0700
  - name: Restart the configuration script
    shell: sfconfig.sh &>> /var/log/software-factory/upgrade.log
  # Managesf database migration
  - include: tasks/managesf_db.yml
  # Cauth database migration
  - include: tasks/cauth_db.yml

- hosts: auth
  tasks:
  - include: tasks/remove_old_service_user.yml

- hosts: jenkins
  tasks:
  - include: tasks/submitconfigreview.yml

- hosts: gerrit
  tasks:
  - include: tasks/allprojectsupdate.yml
  - include: tasks/schemaupdate.yml
  - include: tasks/update_configrepo.yaml
  - name: Propose replication.config in the config repo
    shell: /usr/local/bin/propose_replication_config.sh
