---
- name: "Fetch gerritbot code"
  git: repo={{ gerritbot_url }} dest=/usr/src/gerritbot recursive=no version={{ gerritbot_commit }} update=no force=yes

- name: "Install gerritbot"
  command: chdir=/usr/src/gerritbot /srv/venv/bin/python setup.py install --install-scripts /usr/bin
