---
- group: name=gerritbot
- user: name=gerritbot group=gerritbot shell=/sbin/nologin home=/var/lib/gerritbot

- name: "Create configuration directory"
  file: path={{ item }} state=directory mode=0700 owner=gerritbot group=gerritbot
  with_items:
    - /var/lib/gerritbot
    - /etc/gerritbot

- name: "Init default channels.yaml file"
  copy: src="/usr/local/share/sf-config-repo/gerritbot/channels.yaml" dest="/etc/gerritbot/channels.yaml" remote_src=True force=no

- name: "Configure tmpfiles.d to recreate /var/run/gerritbot after reboot"
  lineinfile: dest=/lib/tmpfiles.d/gerritbot.conf state=present create=yes line='d /var/run/gerritbot 0755 gerritbot gerritbot -'
