description: "Multi jenkins master sample deployment"
inventory:
  - name: node01
    roles:
      - install-server
      - mysql
      - auth
      - gateway
      - managesf
      - statsd
      - redmine
      - zuul
      - nodepool
      - gerrit
  - name: jenkins01
    roles:
      - jenkins
  - name: jenkins02
    roles:
      - jenkins
