---
- name: "Fetch gerrit logs and config"
  synchronize:
    mode: pull
    src: "/home/gerrit/site_path/{{ item }}/"
    dest: "{{ log_dest }}/{{ item }}/"
    rsync_opts: "--exclude mail --exclude ssh_host_*"
  with_items: ["logs", "etc"]
