---
- name: "Remove previous state and git repositories"
  file:
    path: "/var/lib/gerrit/{{ item }}"
    state: absent
  with_items:
    - git
    - cache
    - index

- name: "Restore data"
  synchronize:
    src: "{{ backup_src }}/"
    dest: /
