---
- include_vars: /etc/puppet/hiera/sf/sfcreds.yaml
- include_vars: /etc/puppet/hiera/sf/gerrit.yaml
- include_vars: /etc/puppet/hiera/sf/common.yaml

- name: "Create gerrit user"
  include: /etc/ansible/tasks/create_user.yml user_name=gerrit home_dir=/home/gerrit ssh_key=gerrit_service_rsa shell=/bin/bash

- include: install_plugins.yml

- name: "Copy gerrit service key"
  copy:
      content: "{{ hostvars[inventory_hostname][item.name] }}"
      dest: "/home/gerrit/site_path/etc/{{ item.file }}"
      mode: "{{ item.mode }}"
      owner: gerrit
      group: gerrit
  with_items:
      - {name: gerrit_service_rsa, file: ssh_host_rsa_key, mode: "0400"}
      - {name: gerrit_service_rsa_pub, file: ssh_host_rsa_key.pub, mode: "0444"}

- name: "Copy gerrit admin key"
  copy:
      content: "{{ hostvars[inventory_hostname][item.name] }}"
      dest: "/root/{{ item.file }}"
      mode: "{{ item.mode }}"
      owner: root
      group: root
  with_items:
      - {name: gerrit_admin_rsa, file: gerrit_admin_rsa, mode: "0400"}

- name: "Allow gerrit to connect to himself for self replication"
  authorized_key:
      user: gerrit
      key: "{{ gerrit_service_rsa_pub }}"

- include: install_files.yml

# Seport fail to relabel existing port, see https://github.com/ansible/ansible-modules-extras/issues/2009
#- seport: ports={{ item }} proto=tcp setype=http_port_t state=present
- name: "Selinux: add port for gerrit service"
  command: semanage port --modify -t http_port_t -p tcp {{ item }}
  with_items: [8000]
  when: selinuxenabled

- name: "Initialize gerrit with gerrit user"
  shell: '/usr/bin/java -jar /home/gerrit/gerrit.war init -d /home/gerrit/site_path --batch --no-auto-start'
  become: true
  become_user: gerrit
  register: initialize_done
  when: gerrit_war|changed

- name: "Reindex gerrit after the first initialization"
  shell: '/usr/bin/java -jar /home/gerrit/gerrit.war reindex -d /home/gerrit/site_path'
  become: true
  become_user: gerrit
  when: initialize_done|changed

- name: "Add initial user"
  shell: '/root/gerrit-firstuser-init.sh'
  register: first_user
  when: initialize_done|changed

#- name: "Set ACL"
#  shell: '/root/gerrit-set-default-acl.sh'
#  when: first_user|changed
#
#- name: "Start service"
#  systemd:
#      name: gerrit
#      enabled: yes
#      state: started
#      daemon_reload: yes
