---
- include_vars: /etc/software-factory/sfcreds.yaml
- include_vars: /etc/software-factory/gerrit.yaml
- include_vars: /etc/ansible/roles/sf-redmine/defaults/main.yml
- include_vars: /etc/ansible/vars/common.yml

- name: "Create gerrit user"
  include: /etc/ansible/tasks/create_user.yml user_name=gerrit home_dir=/home/gerrit ssh_key=gerrit_service_rsa shell=/bin/bash

- include: install_files.yml
- include: install_plugins.yml

- name: "Copy gerrit service key"
  copy:
      content: "{{ hostvars[inventory_hostname][item.name] }}"
      dest: "/home/gerrit/site_path/etc/{{ item.file }}"
      mode: "{{ item.mode }}"
      owner: gerrit
      group: gerrit
  with_items:
      - {name: gerrit_service_rsa, file: ssh_host_rsa_key, mode: "0400"}
      - {name: gerrit_service_rsa_pub, file: ssh_host_rsa_key.pub, mode: "0444"}

- name: "Copy gerrit admin key"
  copy:
      content: "{{ hostvars[inventory_hostname][item.name] }}"
      dest: "/root/{{ item.file }}"
      mode: "{{ item.mode }}"
      owner: root
      group: root
  with_items:
      - {name: gerrit_admin_rsa, file: gerrit_admin_rsa, mode: "0400"}

- name: "Allow gerrit to connect to himself for self replication"
  authorized_key:
      user: gerrit
      key: "{{ gerrit_service_rsa_pub }}"

- name: Apply selinux port labelling
  seport:
      ports: 8000
      proto: tcp
      setype: http_port_t
      state: present
  when:
      - selinuxenabled

- name: "Test if gerrit is already installed"
  stat:
      path: /home/gerrit/site_path/bin/gerrit.war
  register: gerrit_war

- name: "Initialize gerrit with gerrit user"
  shell: '/usr/bin/java -jar /home/gerrit/gerrit.war init -d /home/gerrit/site_path --batch --no-auto-start'
  become: true
  become_user: gerrit
  register: initialize_done
  when: gerrit_war.stat.exists == False

- name: "Reindex gerrit after the first initialization"
  shell: '/usr/bin/java -jar /home/gerrit/gerrit.war reindex -d /home/gerrit/site_path'
  become: true
  become_user: gerrit
  when: initialize_done|changed

- name: "Install gerrit service file"
  template:
      src: gerrit.service.j2
      dest: /lib/systemd/system/gerrit.service
      owner: root
      group: root
      mode: 0644

- name: "Start service"
  systemd:
      name: gerrit
      state: started
      daemon_reload: yes
      enabled: yes

- name: "Add initial user"
  shell: 'mysql gerrit < /root/gerrit-firstuser-init.sql'
  register: first_user
  when: initialize_done|changed

- name: "Add jenkins user"
  command: /root/gerrit-set-ci-user.sh
  when: initialize_done|changed

- name: "Set ACL"
  command: /root/gerrit-set-default-acl.sh
  when: initialize_done|changed
