---
- include_vars: /etc/puppet/hiera/sf/sfcreds.yaml
- include_vars: /etc/puppet/hiera/sf/gerrit.yaml

- name: "Create gerrit user"
  include: /etc/ansible/tasks/create_user.yml user_name=gerrit home_dir=/home/gerrit ssh_key=gerrit_service_rsa shell=/bin/bash

- include: install_plugins.yml

- name: "Copy gerrit service key"
  copy:
    content: "{{ hostvars[inventory_hostname][item.name] }}"
    dest: "/home/gerrit/site_path/etc/{{ item.file }}"
    mode: "{{ item.mode }}"
    owner: gerrit
    group: gerrit
  with_items:
    - {name: gerrit_service_rsa, file: ssh_host_rsa_key, mode: "0400"}
    - {name: gerrit_service_rsa_pub, file: ssh_host_rsa_key.pub, mode: "0444"}

- name: "Allow gerrit to connect to himself for self replication"
  authorized_key:
    user: gerrit
    key: "{{ gerrit_service_rsa_pub }}"

- include: install_files.yml

# Seport fail to relabel existing port, see https://github.com/ansible/ansible-modules-extras/issues/2009
#- seport: ports={{ item }} proto=tcp setype=http_port_t state=present
- name: "Selinux: add port for gerrit service"
  command: semanage port --modify -t http_port_t -p tcp {{ item }}
  with_items: [8000]
  when: selinuxenabled

# TODO: need to manage wait4mariadb
# in puppet/modules/systemctl/templates/wait4mariadb
- name: "Install gerrit service file"
  template:
    src: gerrit.service.j2
    dest: /lib/systemd/system/gerrit.service
    owner: root
    group: root
    mode: 0644
