role_actions:
  - install
  - setup
  - get_logs

hash_code: |
    import crypt, random, string, sys
    salt = '\$6\$' + ''.join(random.choice(string.letters + string.digits) for _ in range(16)) + '\$'
    sys.stdout.write(crypt.crypt(

hash_code_end: ", salt))"
