---
# This is main configuration playbook, called by sfconfig.sh
- hosts: all
  tasks:
    - template: src=templates/global_known_hosts.j2 dest=/etc/ssh/ssh_known_hosts owner=root group=root mode=0644
    - file: path=/etc/software-factory state=directory

- hosts: managesf
  tasks:
    - include: tasks/create_config_repository.yaml
    - include: tasks/managesf_authorized_keys.yaml
    - include: tasks/gerritbot.yaml

- include: sf_configrepo_update.yaml

- hosts: murmur
  roles:
    - sf-murmur
