---
- hosts: all
  tasks:
    - template: src=templates/global_known_hosts.j2 dest=/etc/ssh/ssh_known_hosts owner=root group=root mode=0644

- hosts: gerrit
  sudo_user: gerrit
  tasks:
    - name: Override gerrit known host with globals
      command: cp /etc/ssh/ssh_known_hosts /home/gerrit/.ssh/known_hosts

# Redmine rubber-band
- hosts: redmine
  tasks:
    - include: tasks/redmine_rubber_band.yaml
    - include: tasks/redmine_rubber_band.yaml
    - include: tasks/redmine_rubber_band.yaml
    - include: tasks/redmine_rubber_band.yaml

- hosts: managesf
  tasks:
    - include: tasks/create_config_repository.yaml
    - include: tasks/managesf_authorized_keys.yaml

- hosts: jenkins
  tasks:
    - include: tasks/jenkins_update.yaml

- hosts: nodepool
  tasks:
    - include: tasks/nodepool_update.yaml

- hosts: zuul
  tasks:
    - include: tasks/zuul_update.yaml
