role_actions:
  - install
  - setup

kibana_repo_url: https://packages.elastic.co/kibana/4.5/centos

kibana_topmenu_patch: |
  function load_menu() { loadTopmenu(); }
  newScript = document.createElement('script');
  newScript.type = 'text/javascript';
  newScript.src = '/static/js/topmenu.js';
  newScript.onload = load_menu;
  document.getElementsByTagName('head')[0].appendChild(newScript);
