#!/bin/sh

# Configuration was stored in /root/sfconfig.yaml, it needs to be moved to bootstrap-data
mkdir -p /root/sf-bootstrap-data/hiera
mv /root/sfconfig.yaml /root/sf-bootstrap-data/hiera

exit 0
