---
- name: "Fetch code"
  git:
    repo: "{{ nodepool_url }}"
    dest: /usr/src/nodepool
    version: "{{ nodepool_commit }}"
    recursive: no
    update: no

- name: "Install venv"
  command: chdir=/usr/src/nodepool {{ item }}
  with_items:
    - virtualenv /srv/nodepool
    - /srv/nodepool/bin/pip install --upgrade pbr pip
    - sed -i 's/^pbr.*//' requirements.txt
    - /srv/nodepool/bin/pip install 'funcsigs' file:///usr/src/nodepool/
    - /srv/nodepool/bin/python setup.py install

- name: "Install program"
  command: ln -sf /srv/nodepool/bin/{{ item }} /usr/bin/{{ item }}
  with_items: [nodepool, nodepoold]
