---
- name: "Fetch code"
  git:
    repo: "{{ nodepool_url }}"
    dest: /usr/src/nodepool
    version: "{{ nodepool_commit }}"
    recursive: no
    force: yes

- name: "Install venv"
  command: chdir=/usr/src/nodepool {{ item }}
  with_items:
    - virtualenv --system-site-packages /srv/nodepool
    - /srv/nodepool/bin/pip install --upgrade pbr pip
    - sed -i 's/^pbr.*//' requirements.txt
    - sed -i 's/^shade.*/shade==1.9.0/' requirements.txt
    - /srv/nodepool/bin/pip install 'funcsigs' -rrequirements.txt
    - /srv/nodepool/bin/python setup.py install

- name: "Install program"
  command: ln -sf /srv/nodepool/bin/{{ item }} /usr/bin/{{ item }}
  with_items: [nodepool, nodepoold]
