---
- include_vars: /etc/ansible/vars/common.yml
- include: /etc/ansible/tasks/create_user.yml user_name=nodepool ssh_key=jenkins_rsa

- name: "Create /etc/nodepool directory"
  file: path=/etc/nodepool state=directory

- name: "Create /etc/nodepool/scripts directory"
  file: path=/etc/nodepool/scripts state=directory

- name: "Setup configuration"
  template: src="templates/{{ item }}.j2" dest="/etc/nodepool/{{ item }}" mode=0440 group=nodepool
  with_items: ["secure.conf"]

- name: "Setup conf update script"
  template: src=templates/sf-nodepool-conf-update.sh.j2 dest=/usr/local/bin/sf-nodepool-conf-update.sh mode=0755

- name: "Setup localCA"
  copy: content="{{ localCA_pem }}" dest=/etc/nodepool/scripts/localCA.pem

- name: "Apply patch"
  patch: src={{ item }} basedir=/srv/nodepool/lib/python2.7/site-packages strip=1
  with_items:
    - 272097-image-api-use-tasks.patch
    - 321480-Add-log-config-option-to-nodepool-cmd.patch
