---
- include: /etc/ansible/tasks/create_user.yml user_name=nodepool ssh_key=jenkins_rsa

- name: Install templates
  template:
      src: "{{ item.name }}.j2"
      dest: "{{item.dest }}/{{ item.name }}"
      owner: "{{ item.owner | default('root') }}"
      group: "{{ item.group | default('root') }}"
      mode: "{{ item.mode | default(0444) }}"
  with_items:
      - {name: _nodepool.yaml, dest: /etc/nodepool, owner: nodepool}
      - {name: secure.conf, dest: /etc/nodepool, group: nodepool, mode: '0440'}
      - {name: sf-nodepool-conf-update.sh, dest: /usr/local/bin, mode: '0555'}

- name: Install sf-nodepool-conf-merger.py
  copy:
    src: sf-nodepool-conf-merger.py
    dest: /usr/local/bin/sf-nodepool-conf-merger.py
    mode: 0555

- name: Setup sysconfig
  template:
      src: sysconfig.j2
      dest: /etc/sysconfig/nodepool
  notify: nodepool restart
  when: nodepool.disabled == False

- name: Install logging.conf
  template:
      src: logging.conf.j2
      dest: /etc/nodepool/logging.conf

- name: Setup authorized keys
  copy:
      content: "{{ jenkins_rsa_pub }}"
      dest: /etc/nodepool/scripts/authorized_keys

- name: Setup localCA
  copy:
      content: "{{ localCA_pem }}"
      dest: /etc/nodepool/scripts/localCA.pem

- name: Start service
  service: name=nodepool state=started enabled=yes
  when: nodepool.disabled == False
