# Note: '\' character needs to be escapped twice ('\\')
# Double quote needs to be escaped too
commentlinks:
  - name: Redmine_addressing
    match: '([Bb]ug|[Ff]ix|[Ii]ssue|[Cc]loses?):\\s+#?(\\d+)'
    html: '$1 <a href=\"/redmine/issues/$2\">$2</a>'
  - name: Redmine_related
    match: '([Rr]elated|[Rr]elated[ -][Tt]o):\\s+#?(\\d+)'
    html: '$1 <a href=\"/redmine/issues/$2\">$2</a>'
  - name: Story
    match: 'Story: (\\d+)'
    html: 'Story: <a href=\"/storyboard/#!/story/$1\">$1</a>'
