---
- name: "Create /var/www/storyboard"
  file: path=/var/www/storyboard state=directory mode=0755

- name: "Check for pre-installed in /var/www/storyboard-webclient"
  stat: path=/var/www/storyboard/index.html
  register: installed

- name: "Extract pre-built client"
  unarchive: src=https://tarballs.openstack.org/storyboard-webclient/storyboard-webclient-{{ storyboard_webclient_commit }}.tar.gz dest=/var/www/storyboard/ copy=no
  when: installed.stat.exists == false

- name: "Remove dist sub directory"
  shell: "[ -d /var/www/storyboard/dist/ ] && mv /var/www/storyboard/dist/* /var/www/storyboard/ && rm -Rf /var/www/storyboard/dist/"

# Manual build process bellow
#- name: "Install storyboard-webclient code"
#  git: repo=git://git.openstack.org/openstack-infra/storyboard-webclient dest=/srv/storyboard-webclient_git recursive=no version={{ storyboard_webclient_commit }} update=no
#- name: "Create dist files"
#  command: chdir=/srv/storyboard-webclient_git "{{ item }}"
#  with_items:
#    - virtualenv /srv/storyboard-webclient_git/.venv
#    - /srv/storyboard-webclient_git/.venv/bin/pip install --upgrade 'pbr' 'pip<8' 'tox'
#    - /srv/storyboard-webclient_git/.venv/bin/tox -egrunt_no_api -- compile

