---
- name: "Install requirements"
  yum:
    name: "fontawesome-fonts-web,js-jquery1,python-XStatic-Angular,python-XStatic-Bootstrap-SCSS,python-scss,python-pathlib"
    state: present
    disablerepo: "{{ yum_disable_repo|default(omit) }}"
    enablerepo: "{{ yum_enable_repo|default(omit) }}"
  register: csspackages

- name: "Symlink awesome font"
  file:
    src: /usr/share/font-awesome-web
    dest: /var/www/static/font-awesome
    state: link

- name: "Symlink bootstrap"
  file:
    src: /usr/share/javascript/bootstrap_scss
    dest: /var/www/static/bootstrap
    state: link

- name: "Remove bootstrap css directory when packages changed"
  file:
    path: /var/www/static/bootstrap/css
    state: absent
  when: csspackages|changed

- name: "Create bootstrap css directory"
  file:
    path: /var/www/static/bootstrap/css
    state: directory

- name: "Create bootstrap.css"
  command: pyscss /usr/share/javascript/bootstrap_scss/scss/bootstrap.scss -o /var/www/static/bootstrap/css/bootstrap.min.css
  args:
    creates: /var/www/static/bootstrap/css/bootstrap.min/css

- name: "Symlink angular"
  file:
    src: /usr/share/javascript/angular/angular.js
    dest: /var/www/static/js/angular.min.js
    state: link

- name: "Symlink jquery"
  file:
    src: /usr/share/javascript/jquery/1/jquery.min.js
    dest: /var/www/static/js/jquery.min.js
    state: link
