---
- name: "Install logs gearman worker group"
  group: name=joblogsworker

- name: "Install logs gearman worker user"
  user: name=joblogsworker group=joblogsworker shell=/sbin/nologin home=/srv/log-gearman-worker

- name: "Install virtualenv for job logs gearman worker"
  command: "{{ item }}"
  with_items:
    - virtualenv /srv/log-gearman-worker
    - /srv/log-gearman-worker/bin/pip install --upgrade 'pbr' 'pip'
    - /srv/log-gearman-worker/bin/pip install gear statsd PyYAML python-daemon

- name: "Fetch job logs gearman worker from Openstack infra repo"
  get_url: url={{ log_gearman_worker_url }} dest=/srv/log-gearman-worker/bin/log-gearman-worker.py mode=0755

- name: "Create configuration directory"
  file: path=/etc/log-gearman-worker/ state=directory mode=0755

- name: "Create log directory"
  file: path=/var/log/log-gearman-worker/ state=directory mode=0755 owner=joblogsworker group=joblogsworker
