---
- include: /etc/ansible/tasks/create_user.yml user_name=joblogsworker

- name: "Create configuration directory"
  file: path=/etc/log-gearman-worker/ state=directory mode=0755

- name: "Create log directory"
  file: path=/var/log/log-gearman-worker/ state=directory mode=0755 owner=joblogsworker group=joblogsworker

- name: "Install log gearman worker configuration"
  template: src=templates/jenkins-log-worker.yaml.j2 dest=/etc/log-gearman-worker/config.yml owner=joblogsworker group=joblogsworker
  register: config

- name: "Install service file"
  copy:
      src: log-gearman-worker.service
      dest: /usr/lib/systemd/system/log-gearman-worker.service
      owner: root
      group: root
      mode: 0644

- name: "Start service"
  systemd:
      name: log-gearman-worker
      state: started
      daemon_reload: yes
      enabled: yes

- name: "Restart log gearman worker if needed"
  service: name=log-gearman-worker state=restarted
  when: config|changed
