---
- name: "Install logs gearman worker group"
  group: name=joblogsworker

- name: "Install logs gearman worker user"
  user: name=joblogsworker group=joblogsworker shell=/sbin/nologin home=/srv/log-gearman-worker

- name: "Install log gearman worker configuration"
  template: src=templates/jenkins-log-worker.yaml.j2 dest=/etc/log-gearman-worker/config.yml owner=joblogsworker group=joblogsworker
  register: config

- name: Install service file
  copy:
      src: log-gearman-worker.service
      dest: /usr/lib/systemd/system/log-gearman-worker.service
      owner: root
      group: root
      mode: 0644

- name: Start service
  systemd:
      name: log-gearman-worker
      state: started
      daemon_reload: yes
      enabled: yes

- name: "Restart log gearman worker if needed"
  service: name=log-gearman-worker state=restarted
  when: config|changed
