role_actions:
  - install
  - setup
  - update
  - get_logs

storyboardclient_url: https://git.openstack.org/openstack-infra/python-storyboardclient
storyboardclient_commit: master
redmine_api_url: "http://api-redmine.{{ fqdn }}:8083/"
roles: []

managesf_loglevel: INFO
managesf_root_loglevel: WARNING

managesf_port: 20001

managesf_mysql_password: "CHANGE_ME"
