---
- name: "Fetch code"
  git:
    repo: "{{ zuul_url }}"
    dest: /usr/src/zuul
    version: "{{ zuul_commit }}"
    recursive: no
    force: yes

- name: "Fetch javascripts"
  get_url: url={{item.src}} dest=/var/www/static/js/{{item.dst}}
  with_items:
    - {src: "{{jquery_visibility_url}}",  dst: jquery-visibility.min.js}
    - {src: "{{jquery_graphite_url}}",    dst: jquery.graphite.js}

- name: "Install venv"
  command: chdir=/usr/src/zuul {{ item }}
  with_items:
    - virtualenv --system-site-packages /srv/zuul
    - /srv/zuul/bin/pip install --upgrade pbr pip
    - sed -i 's/^pbr.*//' requirements.txt
    - /srv/zuul/bin/pip install -rrequirements.txt
    - /srv/zuul/bin/pip install python-swiftclient python-keystoneclient
    - /srv/zuul/bin/python setup.py install

- name: "Install program"
  command: ln -sf /srv/zuul/bin/{{ item }} /usr/bin/{{ item }}
  with_items: [zuul, zuul-cloner, zuul-merger, zuul-server, zuul-launcher]

- name: "Install web virtualhost"
  synchronize: src=/usr/src/zuul/etc/status/public_html/ dest=/var/www/zuul/ delete=yes
