---
# Use 0751 to let apache access /var/lib/zuul/git
- include: /etc/ansible/tasks/create_user.yml user_name=zuul ssh_key=jenkins_rsa home_dir_mode=0751

- name: Apply selinux port labelling
  seport:
      ports: 8084
      proto: tcp
      setype: http_port_t
      state: present
  when:
      - selinuxenabled

- name: "Apply patch"
  patch: src={{ item }} basedir=/srv/zuul/lib/python2.7/site-packages strip=1
  # ignore_errors because first patch will failed on second run with: Reversed (or previously applied) patch detected
  ignore_errors: yes
  with_items:
    - 152290-Add-support-for-layout-configuration-split.patch
    - 270338-zuul_temp-url-key.patch
    - 0001-Keep-existing-loggers-with-fileConfig.patch
    - 0001-Read-all-Gerrit-events-from-poll-interruption.patch
    - Fix-Third-party-CI-conflict.patch

- name: "Setup apache site zuul.conf"
  template: src=zuul.site.j2 dest=/etc/httpd/conf.d/zuul.conf mode=0444
  notify: apache reload

- name: "Create state directory directory"
  file: path={{ item }} state=directory owner=zuul group=zuul
  with_items:
    - /var/log/zuul
    - /var/run/zuul

- name: "Create /etc/zuul directory"
  file: path=/etc/zuul state=directory

- name: "Touch layout.yaml"
  file: path=/etc/zuul/layout.yaml state=touch

- name: "Copy logging configuration"
  template: src={{ item }}.j2 dest=/etc/zuul/{{ item }}
  with_items:
    - logging.conf
    - gearman-logging.conf
    - merger-logging.conf

- name: "Setup sysconfig"
  template: src=sysconfig.j2 dest=/etc/sysconfig/zuul
  notify: restart zuul

- name: "Setup configuration"
  template: src=zuul.conf.j2 dest=/etc/zuul/zuul.conf mode=0440 group=zuul
  notify: restart zuul

- name: Install service file
  copy:
      src: "{{ item }}.service"
      dest: "/lib/systemd/system/{{ item }}.service"
      owner: root
      group: root
      mode: 0644
  with_items:
    - zuul
    - zuul-merger

- name: Start service
  systemd:
      name: "{{ item }}"
      state: started
      daemon_reload: yes
      enabled: yes
  with_items:
    - zuul
    - zuul-merger

- name: "Copy gearman-check script"
  copy: src=gearman-check dest=/usr/local/bin/gearman-check mode=0555

- name: "Setup gearman-check cron"
  cron: name=gearman-check-cron job=/usr/local/bin/gearman-check minute=0 hour=0
