---
- name: "Fetch code"
  git:
    repo: "{{ germqtt_url }}"
    dest: /usr/src/germqtt
    version: "{{ germqtt_commit }}"
    recursive: no
    force: yes

- name: "Install venv"
  command: chdir=/usr/src/germqtt {{ item }}
  with_items:
    - virtualenv /srv/germqtt
    - /srv/germqtt/bin/pip install --upgrade pbr pip
    - sed -i 's/^pbr.*//' requirements.txt
    - /srv/germqtt/bin/pip install -rrequirements.txt
    - /srv/germqtt/bin/python setup.py install

- name: "Install program"
  command: ln -sf /srv/germqtt/bin/germqtt /usr/bin/germqtt
