- name: Install python-pip
  yum: name=python-pip state=present

- pip: name=devpi-server

- file: path=/var/ftp/ owner=ftp group=ftp state=directory mode=0755

- name: Install service file
  copy: src=../files/devpi.service dest=/lib/systemd/system/devpi.service

- name: Reload units
  command: systemctl daemon-reload

- name: Start devpi service
  service: name=devpi state=started
