---
- name: "Install package"
  yum:
    name: "gitweb, highlight, perl-Digest-MD5, gitweb-theme-kogakure"
    state: latest
    disablerepo: "{{ yum_disable_repo|default(omit) }}"
    enablerepo: "{{ yum_enable_repo|default(omit) }}"

- name: "Set theme in use"
  replace:
    dest: /var/www/git/gitweb.cgi
    regexp: '"static/.*.css"'
    replace: '"static/{{ theme }}.css"'

- name: "Set gitweb config for Gerrit"
  file:
    src: gitweb_config.perl
    dest: /home/gerrit/site_path/etc/gitweb_config.perl
    owner: gerrit
    group: gerrit
