---
# Prepare the edeploy server before the upgrade
- name: Create target directory for install-server-vm
  command: mkdir -p {{ install_path }}/install-server-vm
- name: Create target directory for softwarefactory
  command: mkdir -p {{ install_path }}/softwarefactory
- name: Create metadata directory for metadata
  command: mkdir -p {{ metadata_path }}
- name: Deflate install-server-vm archive
  command: tar -xzf {{ upstream_path }}/install-server-vm-{{ version }}.edeploy -C {{ install_path }}/install-server-vm
  args:
    creates: "{{ install_path }}/install-server-vm/bin/bash"
- name: Deflate softwarefactory archive
  command: tar -xzf {{ upstream_path }}/softwarefactory-{{ version }}.edeploy -C {{ install_path }}/softwarefactory
  args:
    creates: "{{ install_path }}/softwarefactory/bin/bash"
- name: Copy metadata
  shell: cp -LR {{ clone_path }}/edeploy/metadata/{{ from_version }}/* {{ metadata_path }}/
