---
- name: "Fetch lodgeit code"
  git: repo={{ lodgeit_url }} dest=/usr/src/lodgeit recursive=no version={{ lodgeit_commit }} update=no force=yes

- name: "Install lodgeit venv"
  command: chdir=/usr/src/lodgeit {{ item }}
  with_items:
    - virtualenv /srv/lodgeit
    - /srv/lodgeit/bin/pip install --upgrade 'pbr' 'pip'
    - sed -i 's/^pbr.*//' requirements.txt
    - sed -i 's/^SQLAlchemy.*//' requirements.txt
    - /srv/lodgeit/bin/pip install -rrequirements.txt mysql-python SQLAlchemy
    - cp -R lodgeit/ {{ lodgeit_module_path }}
