---
- name: "Install package"
  yum:
    name: "lodgeit"
    state: present
    disablerepo: "{{ yum_disable_repo|default(omit) }}"
    enablerepo: "{{ yum_enable_repo|default(omit) }}"
- name: Install top menu
  lineinfile:
    dest: /usr/lib/python2.7/site-packages/lodgeit/views/layout.html
    insertafter: '^    <script type="text/javascript" src="/static/lodgeit/lodgeit.js"></script>$'
    line: '    <script type="text/javascript" src="/static/js/topmenu.js"></script>'
