---
- include_vars: /etc/puppet/hiera/sf/sfcreds.yaml

- name: Apply selinux port labelling
  seport:
      ports: 5000
      proto: tcp
      setype: http_port_t
      state: present
  when:
      - selinuxenabled

- name: Replace absolute URLs
  replace:
    dest: "{{ lodgeit_module_path }}/views/{{ item }}"
    regexp: "/static/"
    replace: "/static/lodgeit/"
  with_items:
    - layout.html
    - help/advanced.html
    - help/pasting.html

- name: Patch top-menu
  lineinfile:
    dest: "{{ lodgeit_module_path }}/views/layout.html"
    insertbefore: "</head>"
    line: "    <script type=\"text/javascript\" src=\"/static/js/topmenu.js\"></script>"

- name: Copy service file
  copy: src=lodgeit.service dest=/lib/systemd/system/lodgeit.service
  register: service_file

- name: Daemon-reload
  command: systemctl daemon-reload
  when: service_file|changed

- name: Install manage.py
  template: src=manage.py.j2 dest=/usr/bin/lodgeit-manage.py mode=0555
  notify: [restart lodgeit]

- name: Install urls.py
  copy: src=urls.py dest={{ lodgeit_module_path }}/urls.py

- name: Install static link
  file: dest=/var/www/static/lodgeit src={{ lodgeit_module_path }}/static state=link

- name: Setup service
  service: name=lodgeit state=started enabled=yes
