---
- name: "Fetch storyboard code"
  git: repo={{ storyboard_url }} dest=/usr/src/storyboard recursive=no version={{ storyboard_commit }} force=yes

- name: "Install storyboard"
  command: chdir=/usr/src/storyboard /srv/venv/bin/python setup.py install --install-scripts /usr/bin

- name: "Fetch storyboardclient"
  git: repo={{ storyboardclient_url }} dest=/usr/src/python-storyboardclient recursive=no version={{ storyboardclient_commit }} force=yes

- name: "Install storyboardclient"
  command: chdir=/usr/src/python-storyboardclient /srv/venv/bin/python setup.py install --install-scripts /usr/bin

- name: "Fix pbr version issue"
  copy: src=storyboard_pbr_version_fix.py dest=/srv/venv/lib/python2.7/site-packages/storyboardclient/__init__.py
