---
- name: "Fetch storyboard code"
  git: repo={{ storyboard_url }} dest=/usr/src/storyboard recursive=no version={{ storyboard_commit }} update=no
- name: "Install storyboard venv"
  command: chdir=/usr/src/storyboard {{ item }}
  with_items:
    - virtualenv /srv/storyboard
    - /srv/storyboard/bin/pip install --upgrade 'pbr' 'pip' 'setuptools'
    - sed -i 's/^pbr.*//' requirements.txt
    - sed -i 's/^.*storyboardclient.*//' requirements.txt
    - /srv/storyboard/bin/pip install -rrequirements.txt
    - /srv/storyboard/bin/python setup.py install

- name: "Fetch storyboardclient"
  git:
    repo: "{{ storyboardclient_url }}"
    dest: /usr/src/python-storyboardclient
    version: "{{ storyboardclient_commit }}"
    recursive: no
    force: yes

- name: "Install storyboardclient"
  command: chdir=/usr/src/python-storyboardclient {{ item }}
  with_items:
    - sed -i 's/^pbr.*//' requirements.txt
    - /srv/storyboard/bin/pip install -rrequirements.txt
    - /srv/storyboard/bin/python setup.py install

- name: "Fix pbr version issue"
  copy: src=storyboard_pbr_version_fix.py dest=/srv/storyboard/lib/python2.7/site-packages/storyboardclient/__init__.py

- name: "Install storyboard program"
  command: ln -sf /srv/storyboard/bin/{{ item }} /usr/bin/{{ item }}
  with_items:
    - storyboard-db-manage
    - storyboard-api
