---
- name: "Fetch storyboard code"
  git: repo=git://git.openstack.org/openstack-infra/storyboard dest=/usr/src/storyboard recursive=no version={{ storyboard_commit }} update=no
- name: "Install storyboard venv"
  command: chdir=/usr/src/storyboard {{ item }}
  with_items:
    - virtualenv /srv/storyboard
    - /srv/storyboard/bin/pip install --upgrade 'pbr' 'pip<8'
    - /srv/storyboard/bin/pip install 'pip<8' file:///usr/src/storyboard/
    - /srv/storyboard/bin/python setup.py install
- name: "Install storyboard program"
  command: ln -sf /srv/storyboard/bin/{{ item }} /usr/bin/{{ item }}
  with_items:
    - storyboard-db-manage
    - storyboard-api

# Quick install of storyboardclient python module
#- name: "Fetch python-storyboardclient code"
#  git: repo=git://git.openstack.org/openstack-infra/python-storyboardclient dest=/usr/src/python-storyboardclient recursive=no version={{ storyboard_client_commit }} update=no
#- name: "Install python-storyboardclient venv"
#  command: chdir=/usr/src/python-storyboardclient {{ item }}
#  with_items:
#    - virtualenv /srv/storyboardclient
#    - /srv/storyboardclient/bin/pip install --upgrade 'pbr' 'pip<8'
#    - /srv/storyboardclient/bin/pip install 'pip<8' file:///usr/src/python-storyboardclient
#    - /srv/storyboardclient/bin/python setup.py install
#- name: "Install storyboardclient library"
#  command: ln -sf /srv/storyboardclient/lib/python2.7/site-packages/storyboardclient /usr/lib/python2.7/site-packages/storyboardclient
