---
- group: name=storyboard
- user: name=storyboard group=storyboard shell=/sbin/nologin home=/var/lib/storyboard
- file: path=/var/lib/storyboard state=directory mode=0700 owner=storyboard group=storyboard
- file: path=/etc/storyboard state=directory mode=0700 owner=storyboard group=storyboard
- include_vars: /etc/software-factory/sfcreds.yaml

- name: "Install storyboard.conf"
  template: src={{ item }}.j2 dest=/etc/storyboard/{{ item }} owner=storyboard group=storyboard mode=0400
  with_items:
    - storyboard.conf
    - superuser.yaml
    - projects.yaml
    - service_token.sql

- name: "Install logging.conf"
  copy: src=logging.conf dest=/etc/storyboard/logging.conf

- name: "Setup database"
  command: storyboard-db-manage upgrade head

- name: "Setup superusers"
  command: storyboard-db-manage load_superusers /etc/storyboard/superuser.yaml

- name: "Setup initial projects"
  command: storyboard-db-manage load_projects /etc/storyboard/projects.yaml

- name: "Setup service_token"
  command: bash -c "mysql storyboard < /etc/storyboard/service_token.sql"

- name: Install service file
  template:
      src: "{{ item }}.service.j2"
      dest: "/lib/systemd/system/{{ item }}.service"
      owner: root
      group: root
      mode: 0644
  with_items:
    - storyboard
    - storyboard-worker


- name: Start service
  systemd:
      name: storyboard
      state: started
      daemon_reload: yes
      enabled: yes

- block:
  when: storyboard_email_notification
  - name: "Create rabbitmq vhost"
    rabbitmq_vhost: name=/storyboard state=present

  - name: "Add rabbitmq user"
    rabbitmq_user:
      user: storyboard
      vhost: /storyboard
      password: "{{ storyboard_rabbitmq_password }}"
      configure_priv: .*
      write_priv: .*
      read_priv: .*
      state: present

  - name: Start worker service
    systemd:
      name: storyboard-worker
      state: started
      daemon_reload: yes
      enabled: yes
