 - provider: default
   images: []
#   images:
#    - name: centos7
#      base-image: centos7-cloud
#      username: centos
#      private-key: /var/lib/nodepool/.ssh/id_rsa
#      setup: base.sh
#      min-ram: 4096
