---
- name: "Fetch RepoXplorer code"
  git:
    repo={{ repoxplorer_url }}
    dest=/usr/src/repoxplorer
    recursive=no
    version={{ repoxplorer_commit }}
    force=yes

- name: "Install RepoXplorer venv"
  command: chdir=/usr/src/repoxplorer /srv/venv/bin/python setup.py install --install-scripts /usr/bin
