---
- group:
    name=repoxplorer
- user:
    name=repoxplorer
    group=repoxplorer
    shell=/sbin/nologin
    home=/var/lib/repoxplorer
- file:
    path={{ item }}
    state=directory
    mode=0700
    owner=repoxplorer
    group=repoxplorer
  with_items:
    - /var/lib/repoxplorer
    - /var/lib/repoxplorer/git_store
    - /etc/repoxplorer

- name: "Install RepoXplorer default user config files"
  copy:
    src={{ item }}
    dest=/etc/repoxplorer/{{ item }}
    force=no
  with_items:
    - projects.yaml
    - idents.yaml

- name: "Install RepoXplorer default config files"
  copy:
    src={{ item }}
    dest=/etc/repoxplorer/{{ item }}
  with_items:
    - config.py

- name: "Set links to production user config files"
  file:
    src=/etc/repoxplorer/{{ item }}
    dest=/srv/repoxplorer/local/share/repoxplorer/{{ item }}
    state=link
    force=true
  with_items:
    - projects.yaml
    - idents.yaml
    - config.py

- name: "Set links to production data stores"
  file:
    src=/var/lib/repoxplorer/{{ item }}
    dest=/srv/repoxplorer/local/share/repoxplorer/{{ item }}
    state=link
  with_items:
    - git_store

- name: "Install RepoXplorer services files Indexer service"
  copy:
    src={{ item }}
    dest=/lib/systemd/system/{{ item }}
  register: services
  with_items:
    - repoxplorer-webui.service
    - repoxplorer.service
- command: systemctl daemon-reload
  when: services|changed

- name: "Start repoxplorer services"
  service:
    name={{ item }}
    state=restarted
    enabled=yes
  with_items:
    - repoxplorer-webui
    - repoxplorer
