---
# Seport fail to relabel existing port, see https://github.com/ansible/ansible-modules-extras/issues/2009
#- seport: ports={{ item }} proto=tcp setype=http_port_t state=present
- command: semanage port --modify -t http_port_t -p tcp {{ item }}
  with_items: [8083]
  when: selinuxenabled

- name: "ensure directories are created"
  file: path=/var/www/redmine/public/themes/classic/javascripts/ state=directory

- name: "install topmenu theme"
  template:
    src: /etc/ansible/roles/sf-gateway/templates/topmenu.js.j2
    dest: /var/www/redmine/public/themes/classic/javascripts/theme.js
    mode: 0444
