---
# Seport fail to relabel existing port, see https://github.com/ansible/ansible-modules-extras/issues/2009
#- seport: ports={{ item }} proto=tcp setype=http_port_t state=present
- name: "Selinux: check port labelling"
  shell: "semanage port -l | grep -w 'http_port_t.*{{ item }}' > /dev/null"
  register: no_selinux_labelling
  changed_when: "no_selinux_labelling.rc != 0"
  ignore_errors: yes
  with_items: [8083]

- name: "Selinux: port labelling"
  command: semanage port --modify -t http_port_t -p tcp {{ item }}
  with_items: [8083]
  when:
      - selinuxenabled
      - no_selinux_labelling|failed

- name: "ensure directories are created"
  file: path=/var/www/redmine/public/themes/classic/javascripts/ state=directory

- name: "install topmenu theme"
  template:
    src: /etc/ansible/roles/sf-gateway/templates/topmenu.js.j2
    dest: /var/www/redmine/public/themes/classic/javascripts/theme.js
    mode: 0444

- name: "install postconf sql"
  template: src=templates/postconf.sql.j2 dest=/root/redmine-postconf.sql
