---
- include_vars: /etc/puppet/hiera/sf/sf_version.yaml
- include_vars: /etc/puppet/hiera/sf/sfcreds.yaml
- include_vars: /etc/ansible/vars/common.yml

- name: "check /var/www/redmine owner"
  stat: path=/var/www/redmine
  register: redmine_owner

- name: "update ownership"
  command: find /var/www/redmine -uid "{{ redmine_owner.stat.uid }}" -exec chown root:root {} \;
  when: redmine_owner.stat.uid != 0

# Seport fail to relabel existing port, see https://github.com/ansible/ansible-modules-extras/issues/2009
#- seport: ports={{ item }} proto=tcp setype=http_port_t state=present
- command: semanage port --modify -t http_port_t -p tcp {{ item }}
  with_items: [8083]
  when: selinuxenabled

- name: "ensure directories are created"
  file: path=/var/www/redmine/public/themes/classic/javascripts/ state=directory

- name: Install backup procedure
  template: src="{{ item }}.sh.j2" dest="/root/{{ item }}_redmine.sh" mode=0555
  with_items: ["backup", "restore"]

- name: "install topmenu theme"
  template:
    src: /etc/ansible/roles/sf-gateway/templates/topmenu.js.j2
    dest: /var/www/redmine/public/themes/classic/javascripts/theme.js
    mode: 0444

- name: "install postconf sql"
  template: src=templates/postconf.sql.j2 dest=/root/redmine-postconf.sql
  register: sqlpostconf

- name: "install configuration.yml"
  copy: src=configuration.yml dest=/var/www/redmine/config/configuration.yml

- name: "install database.yml"
  template: src=database.yml.j2 dest=/var/www/redmine/config/database.yml group=apache mode=0440

- name: "install redmine.conf"
  template: src=redmine.conf.j2 dest=/etc/httpd/conf.d/redmine.conf

- name: "install monit.conf"
  copy: src=monit dest=/etc/monit.d/redmine
  notify: [restart monit]

- name: "create required directories"
  file: path={{ item }} owner=apache group=apache state=directory
  with_items:
    - /var/www/redmine/log
    - /var/run/passenger
    - /var/run/passenger-instreg

- name: "Create secret token"
  command: bundle exec rake generate_secret_token
  args:
    chdir: /var/www/redmine
    creates: /var/www/redmine/config/initializers/secret_token.rb

- name: "Create db"
  shell: bundle exec rake db:migrate --trace &> /var/www/redmine/log/db_migrate.log
  args:
    chdir: /var/www/redmine
    creates: /var/www/redmine/log/db_migrate.log
  environment:
    RAILS_ENV: production

- name: "Load default data"
  shell: bundle exec rake redmine:load_default_data --trace &> /var/www/redmine/log/default_data.log
  args:
    chdir: /var/www/redmine
    creates: /var/www/redmine/log/default_data.log
  environment:
    RAILS_ENV: production
    REDMINE_LANG: en

- name: "Post conf in mysql"
  shell: mysql redmine < /root/redmine-postconf.sql
  when: sqlpostconf|changed

- name: "Install plugins"
  shell: bundle exec rake redmine:plugins:migrate &> /var/www/redmine/log/plugin_install.log
  args:
    chdir: /var/www/redmine
    creates: /var/www/redmine/log/plugin_install.log
  environment:
    RAILS_ENV: production
    REDMINE_LANG: en

- name: "Install backlog plugins"
  shell: bundle exec rake redmine:backlogs:install
  args:
    chdir: /var/www/redmine
    creates: /var/www/redmine/redmine_backlogs_install.log
  environment:
    RAILS_ENV: production
    REDMINE_LANG: en
    labels: false
    story_trackers: Bug
    task_tracker: Task

- name: "Install backlogs topmenu"
  replace:
    dest: /var/www/redmine/plugins/redmine_backlogs/app/views/layouts/rb.html.erb
    regexp: '^<head>$'
    replace: '<head><script src="/redmine/themes/classic/javascripts/theme.js" type="text/javascript"></script>'

- name: "Remove delte.me"
  file: path=/var/www/redmine/files/delete.me state=absent
