---
# Seport fail to relabel existing port, see https://github.com/ansible/ansible-modules-extras/issues/2009
# seport: ports={{ item }} proto=tcp setype=http_port_t state=present
#   -  with_items: [8081, 8010]
- command: semanage port --modify -t http_port_t -p tcp 8081
  when: selinuxenabled
# special case for 8010 that is not already defined
- shell: |
    semanage port --list | grep 'tcp.*8010' && \
      semanage port --modify -t http_port_t -p tcp 8010 ||
      semanage port --add -t http_port_t -p tcp 8010
  when: selinuxenabled
