---
- group: name=jenkins
- user: name=jenkins group=jenkins shell=/sbin/nologin home=/var/lib/jenkins
- file: path=/var/lib/jenkins/ state=directory mode=0755 owner=jenkins
- file: path=/var/lib/jenkins/plugins state=directory mode=0755 owner=jenkins

# Seport fail to relabel existing port, see https://github.com/ansible/ansible-modules-extras/issues/2009
# seport: ports={{ item }} proto=tcp setype=http_port_t state=present
#   -  with_items: [8081, 8010]
- command: semanage port --modify -t http_port_t -p tcp 8081
  when: selinuxenabled
# special case for 8010 that is not already defined
- shell: |
    semanage port --list | grep 'tcp.*8010' && \
      semanage port --modify -t http_port_t -p tcp 8010 ||
      semanage port --add -t http_port_t -p tcp 8010
  when: selinuxenabled

- name: "Create /etc/jenkins_jobs directory"
  file: path=/etc/jenkins_jobs/ state=directory mode=0500 owner=jenkins

- name: "Setup jenkins_jobs.ini"
  template: src=jenkins_jobs.ini.j2 dest=/etc/jenkins_jobs/jenkins_jobs.ini mode=0400 owner=jenkins group=root

# Setup groovy script
- file: path=/usr/local/share/sf-jenkins-slave-tools/ state=directory mode=0755
- copy: src=remove-offline-node.groovy dest=/usr/local/share/sf-jenkins-slave-tools/remove-offline-node.groovy mode=0444
- include_vars: /etc/puppet/hiera/sf/sfcreds.yaml
- template: src=cron-jenkins-remove-offline-node.sh.j2 dest=/etc/cron.daily/jenkins-remove-offline-node.sh mode=0500

# Setup default configuration for config-check
- name: "Create defconf directory"
  file:  path=/var/lib/jenkins/defconf state=directory mode=0500 owner=jenkins

- include_vars: /etc/puppet/hiera/sf/sfcreds.yaml

- name: "Setup test configuration for zuul and nodepool"
  template: src={{ item }}.j2 dest=/var/lib/jenkins/defconf/{{ item }}
  with_items:
    - zuul.conf
    - nodepool.yaml
