---
# Seport fail to relabel existing port, see https://github.com/ansible/ansible-modules-extras/issues/2009
#- seport: ports={{ item }} proto=tcp setype=http_port_t state=present
- name: "Selinux: check port labelling"
  shell: "semanage port -l | grep -w 'http_port_t.*{{ item }}' > /dev/null"
  register: no_selinux_labelling
  changed_when: "no_selinux_labelling.rc != 0"
  ignore_errors: yes
  with_items: [9001]

- name: Relabel port (selinux)
  command: semanage port --modify -t http_port_t -p tcp {{ item }}
  with_items: [9001]
  when:
      - selinuxenabled
      - no_selinux_labelling|failed
