---
- include: /etc/ansible/tasks/create_user.yml user_name=etherpad

# Seport fail to relabel existing port, see https://github.com/ansible/ansible-modules-extras/issues/2009
#- seport: ports={{ item }} proto=tcp setype=http_port_t state=present
- name: "Selinux: check port labelling"
  shell: "semanage port -l | grep -w 'http_port_t.*{{ item }}' > /dev/null"
  register: no_selinux_labelling
  changed_when: "no_selinux_labelling.rc != 0"
  ignore_errors: yes
  with_items: [9001]
  when: selinuxenabled

- name: Relabel port (selinux)
  command: semanage port --modify -t http_port_t -p tcp {{ item }}
  with_items: [9001]
  when:
      - selinuxenabled
      - no_selinux_labelling|failed

- name: Install backup procedure
  template: src="{{ item }}.sh.j2" dest="/root/{{ item }}_etherpad.sh" mode=0555
  with_items: ["backup", "restore"]

- name: "Copy service file"
  copy: src=etherpad.service dest=/lib/systemd/system/etherpad.service
  register: etherpad_service

- name: "Daemon-reload"
  when: etherpad_service|changed
  command: systemctl daemon-reload

- name: "Create directory"
  file: path={{ item }} owner=etherpad group=etherpad state=directory
  with_items:
    - /var/www/etherpad-lite
    - /var/log/etherpad

- name: "Copy run.sh"
  copy: src=run.sh dest=/var/www/etherpad-lite/run.sh mode=0555

- name: "Copy custom pad.css"
  copy: src=pad.css dest=/var/www/etherpad-lite/src/static/custom/pad.css

- name: "Setup settings.json"
  template: src=settings.json.j2 dest=/var/www/etherpad-lite/settings.json
  notify: [restart etherpad]

- name: "Start service"
  service: name=etherpad state=started enabled=yes
