---
- name: "Add the grafana RPM repository"
  yum_repository:
    name: "{{ grafana_repo_name }}"
    description: "{{ grafana_repo_desc }}"
    baseurl: "{{ grafana_repo_url }}"
    gpgkey: "{{ grafana_repo_gpgkey }}"
    gpgcheck: "{{ grafana_repo_gpgcheck }}"

- name: "Install package"
  yum:
    name: grafana
    state: present
    disablerepo: "*"
    enablerepo: "{{ grafana_repo_name }}"
