---
- name: Copy default JJB definitions
  template: src=templates/_default_jobs.yaml.j2 dest=/usr/local/share/sf-config-repo/jobs/_default_jobs.yaml

- name: Run init-config-repo.sh
  command: /usr/local/bin/init-config-repo.sh init {{ fqdn }} {{ authentication.admin_password }}
