---
- include_vars: /etc/ansible/vars/common.yml

- name: Copy default JJB definitions
  template: src=templates/_default_jobs.yaml.j2 dest=/usr/local/share/sf-config-repo/jobs/_default_jobs.yaml

- name: Install init-config-repo.sh
  template:
      src: "templates/{{ item }}.j2"
      dest: "/usr/local/bin/{{ item }}"
      owner: root
      group: root
      mode: 0555
  with_items:
      - init-config-repo.sh
      - upgrade-config-repo.sh

- name: Run init-config-repo.sh
  command: /usr/local/bin/init-config-repo.sh
