---
- name: "Configure jenkins ssh knownhost for managesf access"
  command: ssh -o BatchMode=yes -o StrictHostKeyChecking=no root@managesf.{{ fqdn }} hostname -f
  sudo_user: jenkins
  sudo: yes

- name: "Configure jenkins access to managesf for backup operation"
  command: ssh -o BatchMode=yes -o StrictHostKeyChecking=no root@managesf.{{ fqdn }} hostname -f
  sudo: yes
  sudo_user: root
