---
- git: repo=http://{{ fqdn }}/r/config dest=/root/config force=yes

- name: Update config repo
  command: chdir=/root/config {{ item }}
  with_items:
    - git fetch --all
    - git reset --hard origin/master --
    - git clean -f -x -d
