---
- file: path=/etc/software-factory/nodepool_config state=touch

- name: Check local config
  command: cat /etc/software-factory/nodepool_config
  register: localconfig

- name: Check upstream config
  command: chdir=/root/config git log --oneline nodepool/
  register: upstreamconfig

- name: Update nodepool configuration
  when: localconfig.stdout != upstreamconfig.stdout
  command: chdir=config {{ item }}
  with_items:
    - /usr/local/bin/sf-nodepool-conf-update.sh apply

- name: Write config repo sha1 matching current configuration
  copy: content="{{ upstreamconfig.stdout }}" dest=/etc/software-factory/nodepool_config
  when: localconfig.stdout != upstreamconfig.stdout
