---
- name: "Configure managesf access to gerrit"
  command: ssh -o StrictHostKeyChecking=no -p 29418 {{ fqdn }}
  register: gerrit
  failed_when: gerrit.stderr.find('Welcome to Gerrit Code Review') == -1

- name: "Configure managesf access to gerrit"
  command: ssh -i /root/sf-bootstrap-data/ssh_keys/gerrit_admin_rsa -o StrictHostKeyChecking=no -p 29418 admin@gerrit.{{ fqdn }}
  register: gerrit
  failed_when: gerrit.stderr.find('Welcome to Gerrit Code Review') == -1
