---

- name: Check if fqdn has been changed
  shell: test `hostname -d` = "{{ fqdn }}"
  register: fqdn_changed
  failed_when: "fqdn_changed.rc > 1"
  changed_when: "fqdn_changed.rc == 1"

- hostname: name=managesf.{{ fqdn }}
  when: fqdn_changed.rc == 1

- name: Remove outdated /usr/share/httpd/.ssh/known_hosts
  file: path=/usr/share/httpd/.ssh/known_hosts state=absent
  when: fqdn_changed.rc == 1

- name: Update config repo with correct fqdn
  when: fqdn_changed.rc == 1
  command: chdir=/root/config {{ item }}
  with_items:
    - sed -i -e 's/host=.*/host={{ fqdn }}/g' .gitreview
    - sed -i -e 's#zuul-cloner http://.*/r#zuul-cloner http://{{ fqdn }}/r#g' jobs/sf_jjb_conf.yaml
    - sed -i -e 's#ssh root@managesf..* /usr/local/bin/sf-config-update.sh#ssh root@managesf.{{ fqdn }} /usr/local/bin/sf-config-update.sh#g' jobs/sf_jjb_conf.yaml
    - git add .gitreview jobs/sf_jjb_conf.yaml
    - git commit -m "Update with new fqdn"
    - git push git+ssh://{{ fqdn }}:29418/config master

- name: Restart zuul service
  when: fqdn_changed.rc == 1
  service: name=zuul state=restarted

- name: Restart zuul-merger service
  when: fqdn_changed.rc == 1
  service: name=zuul-merger state=restarted

- name: Reset Gerrit SSH user keys
  when: fqdn_changed.rc == 1
  shell: "{{ item }}"
  with_items:
    - mysql gerrit < /root/gerrit-restore-user-keys.sql
    - systemctl restart gerrit
    - /root/wait4gerrit.sh
