---
- file: path=/etc/zuul/layout.d state=directory

- file: path=/etc/software-factory/zuul_config state=touch

- name: Check local config
  command: cat /etc/software-factory/zuul_config
  register: localconfig

- name: Check upstream config
  command: chdir=/root/config git log --oneline zuul/
  register: upstreamconfig

- include: zuul_reload.yaml
  when: localconfig.stdout != upstreamconfig.stdout

- name: Write config repo sha1 matching current configuration
  copy: content="{{ upstreamconfig.stdout }}" dest=/etc/software-factory/zuul_config
  when: localconfig.stdout != upstreamconfig.stdout
