---
- include: update_configrepo.yaml

- name: Update zuul layout
  command: chdir=/root/config {{ item }}
  with_items:
    - bash -c "/usr/local/bin/yaml-merger.py zuul | tee /etc/zuul/layout.yaml"
    - bash -c "cp zuul/*.py /etc/zuul/ || true"

- name: Enable slave reuse when nodepool is not enabled
  when: nodepool.disabled
  replace: dest=/etc/zuul/layout.yaml regexp='set_node_options' replace='set_node_reuse'

- name: Start or reload zuul service
  shell: systemctl status zuul && systemctl reload zuul || systemctl start zuul

# Reload doesn't start service see: https://github.com/ansible/ansible/issues/4448
- service: name=zuul state=started enabled=yes
- service: name=zuul-merger state=started enabled=yes
