---
- name: "Backup data"
  synchronize:
    mode: pull
    src: "{{ item }}"
    dest: "{{ backup_dest }}/"
    delete: yes
    rsync_opts: --relative
  with_items:
    - /etc/software-factory/sfconfig.yaml
    - /etc/software-factory/sfcreds.yaml
    - /root/sf-bootstrap-data
    - /root/config
