---

- name: Initalize version control for yaml files
  shell: git init .; git add *; git commit -m 'init'
  args:
      chdir: /etc/software-factory/
      creates: /etc/software-factory/.git

- name: Initialize bup
  command: bup init
  args:
    chdir: /root
    creates: /root/.bup/HEAD

- name: Install backup trigger job
  copy:
    src: files/trigger_backup.sh
    dest: /usr/local/bin/trigger_backup.sh
    mode: 0700

- name: Install crontab for backup nightly job
  cron:
    name: backup_gerrit
    job: /usr/local/bin/trigger_backup.sh
    user: root
    minute: 0
    hour: 1

- name: Start rsyncd
  service: name=rsyncd state=started enabled=yes
