---
- include_vars: /etc/puppet/hiera/sf/sfconfig.yaml

- name: Initalize version control for hiera files
  shell: git init .; git add *; git commit -m 'init'
  args:
      chdir: /etc/puppet/hiera/sf/
      creates: /etc/puppet/hiera/sf/.git

- name: Initialize bup
  command: bup init
  args:
    chdir: /root
    creates: /root/.bup/HEAD

- name: Install backup procedure
  template: src="{{ item }}.sh.j2" dest="/root/{{ item }}_backup.sh" mode=0555
  with_items: ["backup", "restore"]

- name: Install backup trigger job
  copy:
    src: "{{ item.name }}"
    dest: "/usr/local/bin/{{ item.name }}"
    mode: "{{ item.mode | default('0744') }}"
  with_items:
      - {name: trigger_backup.sh, mode: '0700'}
      - {name: export_backup_swift.sh}

- name: Install auto_backup.conf
  template:
      src: auto_backup.conf.j2
      dest: /etc/auto_backup.conf
      mode: 0444

- name: Install crontab for backup nightly jobs
  cron:
    name: "{{ item.name }}"
    job: "{{ item.job }}"
    user: root
    hour: "{{ item.hour }}"
    minute: "{{ item.minute }}"
  with_items:
      - {name: backup_gerrit, job: /usr/local/bin/trigger_backup.sh, hour: "1", minute: "0"}
      - {name: auto_backup, job: /usr/local/bin/export_backup_swift.sh, hour: "5", minute: "0"}

- name: Start rsyncd
  service: name=rsyncd state=started enabled=yes
