---
- name: "Install cauth venv"
  command: chdir=/usr/src/cauth {{ item }}
  with_items:
    - virtualenv /var/www/cauth
    - /var/www/cauth/bin/pip install --upgrade 'pbr' 'pip'
    - sed -i 's/^.*pysflib.*//' requirements.txt
    - sed -i 's/^paramiko.*/paramiko<2/' requirements.txt
    - /var/www/cauth/bin/pip install -rrequirements.txt
    - /var/www/cauth/bin/python setup.py install

- name: "Install pysflib"
  command: chdir=/usr/src/pysflib {{ item }}
  with_items:
    - /var/www/cauth/bin/pip install -rrequirements.txt
    - /var/www/cauth/bin/python setup.py install
