---
# Synchronize the FS with eDeploy
- name: Put profile in vars for edeploy
  shell: mkdir -p /var/log/edeploy && echo 'PROFILE=none' > /var/log/edeploy/vars
- name: Check role version with eDeploy
  command: edeploy version
  register: result
- name: Synchronize FS with eDeploy
  command: edeploy upgrade {{ version }}
  when: result.stdout == '{{ from_version }}'
