---
- include: /etc/ansible/tasks/create_user.yml user_name=murmur

- template: src=../files/murmur.ini.j2 dest=/etc/murmur.ini owner=murmur group=murmur mode=0400
  register: murmur_ini

- name: Super user password
  command: /usr/local/murmur/murmur.x86 -ini /etc/murmur.ini -supw {{ mumble['super_user_password'] }}

- service: name=murmurd state=started enabled=yes

- service: name=murmurd state=restarted
  when: murmur_ini|changed
