---
- name: "Fetch code"
  git:
    repo: "{{ lecm_url }}"
    dest: /usr/src/lecm
    version: "{{ lecm_commit }}"
    recursive: no
    force: yes

- name: "Install lecm"
  command: chdir=/usr/src/lecm /srv/venv/bin/python setup.py install --install-scripts /usr/bin
