---
- name: "Fetch code"
  git:
    repo: "{{ lecm_url }}"
    dest: /usr/src/lecm
    version: "{{ lecm_commit }}"
    recursive: no
    force: yes

- name: "Install venv"
  command: chdir=/usr/src/lecm {{ item }}
  with_items:
    - virtualenv /srv/lecm
    - /srv/lecm/bin/pip install --upgrade 'pbr' 'pip'
    - /srv/lecm/bin/pip install -I 'setuptools=={{ lecm_setuptools_version }}'
    - /srv/lecm/bin/pip install -rrequirements.txt
    - /srv/lecm/bin/python setup.py install

- name: "Install program"
  command: ln -sf /srv/lecm/bin/{{ item }} /usr/bin/{{ item }}
  with_items: [acme-tiny, lecm]
