---
- name: "Setup configuration"
  template: src=lecm.conf.j2 dest=/etc/lecm.conf

- name: "Setup apache redirection"
  template: src=gateway-lecm.conf.j2 dest=/etc/httpd/conf.d/gateway-lecm.conf
  register: lecmgateway

- name: "Ensure apache is up"
  service: name=httpd enabled=yes state=started

- name: "Check if apache is running"
  command: systemctl -q is-active httpd
  register: _httpd
  failed_when: _httpd.rc != 3 and _httpd.rc != 0

- name: "Reload apache"
  service: name=httpd state=reloaded
  when: lecmgateway|changed and _httpd.rc == 0

- name: "Ensure certificate are generated"
  command: lecm --generate
  args:
    creates: /etc/letsencrypt/pem/{{ fqdn }}.pem

- name: "Install renew crontab"
  cron:
    name: "Renew let's encrypt with lecm"
    special_time: weekly
    job: lecm --renew
