role_actions:
  - setup
  - update
  - get_logs

jenkins_internal_url: "http://jenkins.{{ fqdn }}:8081/jenkins/"
jenkins_api_url: "http://jenkins.{{ fqdn }}:8080/jenkins/"
jenkins_pub_url: "{{ gateway_url }}/jenkins/"
jenkins_password: "{{ creds_jenkins_user_password }}"
