role_actions:
  - setup
  - update
  - get_logs
  - backup
  - restore

jenkins_heap_limit: 256m

jenkins_api_port: 8080
jenkins_http_port: 8081
jenkins_port: 8082

jenkins_internal_url: "http://localhost:{{ jenkins_port }}/jenkins/"
jenkins_api_url: "http://example.com:{{ jenkins_api_port }}/jenkins/"
jenkins_pub_url: "https://example.com/jenkins/"

jenkins_password: "CHANGE_ME"
