---
- include_vars: /etc/puppet/hiera/sf/sfcreds.yaml

- name: Create /var/www/cauth
  file:
      path: /var/www/cauth
      state: directory
      owner: apache
      group: apache
      mode: 0750
      setype: httpd_sys_content_t

- name: Install cauth private key
  copy:
    content: "{{ privkey_pem }}"
    dest: /srv/cauth_keys/privkey.pem
    owner: root
    group: apache
    mode: 0440
    setype: httpd_sys_content_t
