role_actions:
  - install
  - setup
  - update
  - get_logs

puppet_modules: zuul
jquery_visibility_url: http://status.openstack.org/jquery-visibility.min.js
jquery_graphite_url: http://status.openstack.org/jquery-graphite.js
zuul_url: https://git.openstack.org/openstack-infra/zuul
zuul_commit: master

zuul_pub_url: "{{ gateway_url }}/zuul/"
zuul_internal_url: "http://zuul.{{ fqdn }}:8084/"
