resources:
  projects: {}
  repos:
    77ad454f-a534-4a3b-8ae6-78fde5030b6e:
      name: config
      description: Config repository (Do not delete it)
      acl: 51bd5183-7e82-4737-8abd-54bbf1a6aea4
  acls:
    51bd5183-7e82-4737-8abd-54bbf1a6aea4:
      file: |
        [access "refs/*"]
          read = group config-core
          owner = group config-ptl
        [access "refs/heads/*"]
          label-Code-Review = -2..+2 group config-core
          label-Code-Review = -2..+2 group config-ptl
          label-Verified = -2..+2 group config-ptl
          label-Workflow = -1..+1 group config-core
          label-Workflow = -1..+1 group config-ptl
          label-Workflow = -1..+0 group Registered Users
          submit = group config-ptl
          read = group config-core
          read = group Registered Users
        [access "refs/meta/config"]
          read = group config-core
          read = group Registered Users
        [receive]
          requireChangeId = true
        [submit]
          mergeContent = false
          action = fast forward only
      groups:
        - ec0fcbfb-09d7-4379-9e6d-6ad377720d77
        - 3ef29c69-37fa-480f-bd4a-aabaf8256c3b
  groups:
    ec0fcbfb-09d7-4379-9e6d-6ad377720d77:
      name: config-ptl
      description: Team lead for the config repo
      members:
        - admin@sftests.com
    3ef29c69-37fa-480f-bd4a-aabaf8256c3b:
      name: config-core
      description: Team core for the config repo
      members: []
