---
- hosts: managesf
  gather_facts: False
  remote_user: root
  tasks:
  - include_vars: rename-rules.yaml
  - name: "Copy rename-groups.sh script"
    copy: src=rename-groups.sh dest=/tmp/rename-groups.sh mode=755
  - name: "Stop zuul"
    shell: systemctl stop zuul
  - name: "Stop zuul-merger"
    shell: systemctl stop zuul-merger
  - name: "Stop gerrit"
    shell: systemctl stop gerrit
  - wait_for: port=29418 state=absent

  - name: "Copy Gerrit SQL commands"
    template:
      src: gerrit.j2
      dest: /tmp/gerrit.sql
      mode: 755

  - name: "Copy Redmine SQL commands"
    template:
      src: redmine.j2
      dest: /tmp/redmine.sql
      mode: 755

  - name: "Rename project in DB"
    mysql_db: state=import name={{ item}} target=/tmp/{{ item }}.sql
    with_items:
      - gerrit
      - redmine

  - file: path=/home/gerrit/site_path/git/ state=directory mode=0755 owner=gerrit recurse=yes

  - name: Check if old git directory exists
    stat: path=/home/gerrit/site_path/git/{{ item.old }}.git
    with_items: repos
    register: gitdir

  - name: Ensure new git directory (needed if namespace used) exists
    file: path=/home/gerrit/site_path/git/{{ item.new | dirname }} state=directory
    with_items: repos

  - name: Rename git directory
    command: mv /home/gerrit/site_path/git/{{ item.old }}.git /home/gerrit/site_path/git/{{ item.new }}.git
    with_items: repos
    when: gitdir.results[0].stat.exists is defined and gitdir.results[0].stat.exists == true

  # Section name can't have '/' to be managed by managesf
  - name: Update section name in /home/gerrit/site_path/etc/replication.config
    replace:
      dest=/home/gerrit/site_path/etc/replication.config
      regexp='(\[remote .){{ item.old | regex_replace('/', '_') }}(.*)'
      replace='\1{{ item.new | regex_replace('/', '_') }}\2'
      backup=yes
    with_items: repos

  # Alias name can't have '/' as the alias name is used as a path for the private key
  - name: Update alias name in url /home/gerrit/site_path/etc/replication.config
    replace:
      dest=/home/gerrit/site_path/etc/replication.config
      regexp='(url = git@alias_gh_){{ item.old | regex_replace('/', '_') }}(.*)'
      replace='\1{{ item.new | regex_replace('/', '_') }}\2'
      backup=yes
    with_items: repos

  - name: Update project name in /home/gerrit/site_path/etc/replication.config
    replace:
      dest=/home/gerrit/site_path/etc/replication.config
      regexp='(projects = ){{ item.old }}(.*)'
      replace='\1{{ item.new }}\2'
      backup=yes
    with_items: repos

  - name: Check if .ssh/config exists
    stat: path=/home/gerrit/.ssh/config
    register: sshconfig
  - name: Update projectname in /home/gerrit/.ssh/config
    replace:
      dest=/home/gerrit/.ssh/config
      regexp='(.*alias_gh_){{ item.old | regex_replace('/', '_') }}(.*)'
      replace='\1{{ item.new | regex_replace('/', '_') }}\2'
      backup=yes
    with_items: repos
    when: sshconfig.stat.exists == true 

  - name: Check if there is a SSH replication key to rename
    stat: path=/home/gerrit/.ssh/alias_gh_{{ item.old | regex_replace('/', '_') }}.key
    with_items: repos
    register: sshkeyfile

  - name: Rename replication SSH key
    command: mv /home/gerrit/.ssh/alias_gh_{{ item.old | regex_replace('/', '_') }}.key /home/gerrit/.ssh/alias_gh_{{ item.new | regex_replace('/', '_') }}.key
    with_items: repos
    when: sshkeyfile.results[0].stat.exists is defined and sshkeyfile.results[0].stat.exists == true

  - name: "Start re-index"
    shell: java -jar /home/gerrit/site_path/bin/gerrit.war reindex -d /home/gerrit/site_path

  - name: "Start gerrit"
    shell: systemctl start gerrit
  - wait_for: port=29418 state=present

  - name: "Start rename project groups for {{ item.new }}"
    shell: "/tmp/rename-groups.sh {{ item.old }} {{ item.new }}"
    with_items: repos
  - name: "Start zuul"
    shell: systemctl start zuul
  - name: "Start zuul merger"
    shell: systemctl start zuul-merger
