---
# * Create a new project
# * Add jobs and zuul layout to config repo
# * Verify config-update
# * Submit a bad change and verify Jenkins CI -1
# * Fix bad change and verify Jenkins CI +1
# * Check if change got merged

- name: "Create project"
  include: playbooks/managesf_project_create.yaml

- name: "Check if jenkins exists"
  include: playbooks/jenkins_check_job.yaml job="{{ check[0] }}"

- name: "Reset config repos"
  include: playbooks/config_reset.yaml
  when: job_created.stat.isdir is not defined

- hosts: install-server
  tasks:
    - name: "Add config repo files"
      when: job_created.stat.isdir is not defined
      template: src=templates/{{ item.template }}.j2 dest=/root/config/{{ item.dest }}
      with_items:
        - { template: "health-jobs.yaml", dest: "jobs/health-{{ node }}.yaml" }
        - { template: "project-layout.yaml", dest: "zuul/{{ project|replace('/', '_')}}.yaml" }
        - { template: "project-jobs.yaml", dest: "jobs/{{ project|replace('/', '_')}}.yaml" }
    - name: "Commit change"
      command: chdir=/root/config bash -c "git add */*.yaml; exec git commit -a -m 'Add {{ project }} to config repo'"
      when: job_created.stat.isdir is not defined

- name: "Submit config repos"
  include: playbooks/config_submit_change.yaml
  when: job_created.stat.isdir is not defined

- hosts: install-server
  tasks:
    - name: Commit bad change and check for test error
      command: chdir={{ project_path }} {{ item }}
      with_items:
        - 'bash -c "(echo exit 1; date) > run_tests.sh"' # Add date to prevent (no new changes reject)
        - 'bash -c "(echo exit 1; date) > run_functional-tests.sh"'
        - 'chmod +x run_tests.sh run_functional-tests.sh'
        - 'git add run_tests.sh run_functional-tests.sh'
        - 'git commit -m "Test {{ project }} repo"'
        - 'submit_and_wait.py --failure'

    - name: "Update change and check for test SUCCESS"
      command: chdir={{ project_path }} {{ item }}
      with_items:
        - 'bash -c "(echo exit 0; date) > run_tests.sh"' # Add date to prevent (no new changes reject)
        - 'bash -c "(echo exit 0; date) > run_functional-tests.sh"'
        - 'git commit -a --amend'
        - 'submit_and_wait.py --approve'
        - 'git fetch --all'
      environment: {'EDITOR':'test'}

    - name: "Check change was merged"
      command: chdir={{ project_path }} git diff HEAD origin/master
      register: diff
      failed_when: diff.stdout != ''

# TODO: remove project and cleanup config-repo when: keep == false
