role_actions:
  - install
  - setup

storyboard_url: https://git.openstack.org/openstack-infra/storyboard
storyboard_commit: master

storyboardclient_url: https://git.openstack.org/openstack-infra/python-storyboardclient
storyboardclient_commit: master

storyboard_email_notification: True
storyboard_rabbitmq_password: "{{ creds_storyboard_rabbitmq_password }}"

storyboard_services:
  - storyboard
  - storyboard-worker
