role_actions:
  - install
  - setup

storyboard_url: https://git.openstack.org/openstack-infra/storyboard
storyboard_commit: master

storyboardclient_url: https://git.openstack.org/openstack-infra/python-storyboardclient
storyboardclient_commit: master

storyboard_service_token: "CHANGE_ME"

storyboard_mysql_host: "mysql.example.com"
storyboard_mysql_port: 3306
storyboard_mysql_db: "storyboard"
storyboard_mysql_user: "storyboard"
storyboard_mysql_password: "CHANGE_ME"

storyboard_email_notification: True
storyboard_rabbitmq_password: "CHANGE_ME"

storyboard_services:
  - storyboard
  - storyboard-worker
