---
- name: "Add the logstash RPM repository"
  yum_repository:
    name: logstash
    description: Logstash repository
    baseurl: "{{ logstash_repo_url }}"

- name: "Install logstash package"
  yum:
    name: logstash
    state: latest
