# This is the base jobs for interacting with a koji
# build system. To be able to run them be sure
# your image is prepared with kojiclient-base.sh

- builder:
    name: prepare-kojiclient-workspace
    builders:
      - shell: |
          # Set koji client identity
          echo "Set Koji client identity"
          tar -xzf ${CLIENTSECRET} -C /home/jenkins/

- builder:
    name: 'base-pkg-validation'
    defaults: global
    builders:
      - prepare-kojiclient-workspace
      - shell: |
          REPOS_CLONE_URL={reposcloneurl} /var/lib/koji-jobs/pkg-validate.sh {buildtarget} {kojicmd}

- builder:
    name: 'base-pkg-exportation'
    defaults: global
    builders:
      - prepare-kojiclient-workspace
      - shell: |
          REPOS_CLONE_URL={reposcloneurl} /var/lib/koji-jobs/pkg-export.sh {buildtarget} {kojicmd}

#- job:
#    name: 'package-validate'
#    defaults: global
#    builders:
#      - base-pkg-validation:
#          buildtarget: "dist-centos7"
#          kojicmd: "koji"
#          reposcloneurl: "http://sftests.com/r"
#      - shell: |
#          echo "Built RPM have been fetched. Additionnal tests can be done here."
#    triggers:
#      - zuul
#    wrappers:
#      - credentials-binding:
#        - file:
#           credential-id: ID_TO_THE_CERTS_ARCHIVE
#           variable: CLIENTSECRET
#    node: base-centos7
#
#- job:
#    name: 'package-export'
#    defaults: global
#    builders:
#      - base-pkg-exportation:
#          buildtarget: "dist-centos7"
#          kojicmd: "koji"
#          reposcloneurl: "http://sftests.com/r"
#      - shell: |
#          echo "Exported !. Nothing more to do here."
#    triggers:
#      - zuul
#    wrappers:
#      - credentials-binding:
#        - file:
#           credential-id: ID_TO_THE_CERTS_ARCHIVE
#           variable: CLIENTSECRET
#    node: base-centos7
