---
- hosts: services
  gather_facts: no
  tasks:
  - include: tasks/puppetagentstop.yml
  - include: tasks/stopsfservices.yml
- hosts: puppetmaster
  gather_facts: no
  tasks:
  - include: tasks/puppetagentstop.yml
  - name: Stop puppet server
    service: name=httpd state=stopped
  - include: tasks/fetchupstream.yml
  - include: tasks/edeployserver.yml
  - include: tasks/edeploysync.yml
