---
- hosts: others
  tasks:
  - include: tasks/puppetagentstop.yml
- hosts: puppetmaster
  tasks:
  - include: tasks/puppetagentstop.yml
  - name: Stop puppet server
    service: name=httpd state=stopped
  - include: tasks/edeployserver.yml
  - include: tasks/edeploysync.yml
- hosts: others
  tasks:
  - include: tasks/edeploysync.yml
- hosts: puppetmaster
  tasks:
  - name: Start the puppet master
    service: name=httpd state=started
  - name: Restart the bootstrap script
    shell: INITIAL=no HOME=/root/ SFSUFFIX={{ domain }} ./bootstrap.sh
    args:
      chdir: /root/puppet-bootstrapper
