puppetmaster:
  :roles:
    - base
    - edeploy
    - ntp
  :username: root
  :hostname: puppetmaster.tests.dom

redmine:
  :roles:
    - base
    - redmine
    - postfix
    - ntp
  :username: root
  :hostname: redmine.tests.dom

mysql:
  :roles:
    - base
    - mysql
    - postfix
    - ntp
  :username: root
  :hostname: mysql.tests.dom

gerrit:
  :roles:
    - base
    - gerrit
    - postfix
    - ntp
  :username: root
  :hostname: gerrit.tests.dom

jenkins:
  :roles:
    - base
    - jenkins
    - postfix
    - ntp
  :username: root
  :hostname: jenkins.tests.dom

managesf:
  :roles:
    - base
    - managesf
    - commonservices
    - ntp
  :username: root
  :hostname: managesf.tests.dom
