puppetmaster:
  :roles:
    - base
    - edeploy
    - roleversion
    - ntp
  :username: root
  :hostname: puppetmaster.tests.dom
  :roleversion: C7.0-1.0.4

redmine:
  :roles:
    - base
    - redmine
    - postfix
    - roleversion
    - ntp
  :username: root
  :hostname: redmine.tests.dom
  :roleversion: C7.0-1.0.4

mysql:
  :roles:
    - base
    - mysql
    - postfix
    - roleversion
    - ntp
  :username: root
  :hostname: mysql.tests.dom
  :roleversion: C7.0-1.0.4

gerrit:
  :roles:
    - base
    - gerrit
    - postfix
    - roleversion
    - ntp
  :username: root
  :hostname: gerrit.tests.dom
  :roleversion: C7.0-1.0.4

jenkins:
  :roles:
    - base
    - jenkins
    - postfix
    - roleversion
    - ntp
  :username: root
  :hostname: jenkins.tests.dom
  :roleversion: C7.0-1.0.4

managesf:
  :roles:
    - base
    - managesf
    - commonservices
    - roleversion
    - ntp
  :username: root
  :hostname: managesf.tests.dom
  :roleversion: C7.0-1.0.4
  :sfversion: 1.0.4
