puppetmaster:
  :roles:
    - base
    - edeploy
    - roleversion
    - ntp
  :username: root
  :hostname: puppetmaster
  :roleversion: C7.0-0.9.3

redmine:
  :roles:
    - base
    - redmine
    - postfix
    - roleversion
    - ntp
  :username: root
  :hostname: redmine
  :roleversion: C7.0-0.9.3

mysql:
  :roles:
    - base
    - mysql
    - postfix
    - roleversion
    - ntp
  :username: root
  :hostname: mysql
  :roleversion: C7.0-0.9.3

gerrit:
  :roles:
    - base
    - gerrit
    - postfix
    - roleversion
    - ntp
  :username: root
  :hostname: gerrit
  :roleversion: C7.0-0.9.3

jenkins:
  :roles:
    - base
    - jenkins
    - postfix
    - roleversion
    - ntp
  :username: root
  :hostname: jenkins
  :roleversion: C7.0-0.9.3

managesf:
  :roles:
    - base
    - managesf
    - commonservices
    - roleversion
    - ntp
  :username: root
  :hostname: managesf
  :roleversion: C7.0-0.9.3
  :sfversion: 0.9.3
