redmine:
  :roles:
    - base
    - redmine
    - postfix
    - ntp
  :username: root
  :hostname: redmine

mysql:
  :roles:
    - base
    - mysql
    - postfix
    - ntp
  :username: root
  :hostname: mysql

gerrit:
  :roles:
    - base
    - gerrit
    - postfix
    - ntp
  :username: root
  :hostname: gerrit

jenkins01:
  :roles:
    - base
    - jenkins
    - postfix
    - ntp
  :username: root
  :hostname: jenkins01

zuul:
  :roles:
    - base
    - zuul
  :username: root
  :hostname: zuul

nodepool:
  :roles:
    - base
    - nodepool
  :username: root
  :hostname: nodepool

managesf:
  :roles:
    - base
    - managesf
    - commonservices
    - ntp
  :username: root
  :hostname: managesf
