---
- hosts: puppetmaster
  gather_facts: no
  tasks:
  - include: tasks/fetchupstream.yml
  - include: tasks/edeployserver.yml
- hosts: services
  gather_facts: no
  tasks:
  - include: tasks/puppetagentstop.yml
  - include: tasks/stopsfservices.yml
- hosts: puppetmaster
  gather_facts: no
  tasks:
  - include: tasks/puppetagentstop.yml
  - name: Stop puppet server
    service: name=httpd state=stopped
  - include: tasks/edeploysync.yml
- hosts: mysql
  gather_facts: no
  tasks:
  - name: convert redmine db to utf8
    script: tasks/redmine_utf8_conversion.sh

