---
- include_vars: /etc/ansible/vars/common.yml
- name: "Set /var/www/managesf context"
  file: path=/var/www/managesf state=directory mode=0750 owner=apache group=apache setype=httpd_sys_content_t

- name: "Create /var/lib/managesf"
  file: path=/var/lib/managesf state=directory mode=0700 owner=apache group=apache

- name: "Copy config-update ssh key"
  copy:
    content: "{{ jenkins_rsa }}"
    dest: "/var/lib/managesf/jenkins_rsa"
    mode: 0400
    owner: apache
    group: apache

- name: "Copy app.wsgi"
  copy: src=app.wsgi dest=/var/www/managesf/app.wsgi

- name: "Setup config.py"
  template: src=templates/config.py.j2 dest=/var/www/managesf/config.py owner=root group=apache mode=0440

- name: "Initialize bup"
  shell: "/usr/local/bin/bup init"
  args:
      chdir: /root
      creates: /root/.bup/HEAD
