role_actions:
  - install
  - update
  - setup
  - get_logs

welcome_page_path: "sf/welcome.html"

# Base64 encoded logo data
gateway_topmenu_logo_data: ""
gateway_favicon_data: ""
gateway_splash_image_data: ""
