---
- name: Set character_set_server to utf8
  lineinfile:
      dest: /etc/my.cnf
      line: "character_set_server = utf8"

- name: Start service
  service: name=mariadb enabled=yes state=started

- name: Check mysql root password
  shell: "/usr/bin/mysqladmin -u root -p{{ mysql_root_password }} status"
  register: mysql_root_password_set
  ignore_errors: True

- name: Set mysql root password
  shell: "/usr/bin/mysqladmin -u root password {{ mysql_root_password }}"
  register: result
  until: result.rc == 0
  retries: 5
  delay: 1
  when: mysql_root_password_set|failed

- name: Install initialization scripts
  template:
    src: "{{ item.name }}.j2"
    dest: "/root/{{ item.realname | default(item.name) }}"
    owner: root
    group: root
    mode: "{{ item.mode | default('0555')}}"
  with_items:
    - { name: create_databases.sql }
    - { name: client.cnf, realname: .my.cnf, mode: '0400' }

- name: ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent
  with_items:
    - localhost
    - "{{ ansible_hostname }}"

- name: remove useless databases if present
  mysql_db:
      name: "{{ item }}"
      state: absent
  with_items:
      - test

- name: Create databases
  shell: "mysql < /root/create_databases.sql"
