---
- include_vars: /etc/puppet/hiera/sf/sfcreds.yaml

- name: Set character_set_server to utf8
  lineinfile:
      dest: /etc/my.cnf
      line: "character_set_server = utf8"

- name: Start service
  service: name=mariadb enabled=yes state=started

- name: Update mysql root password for all root accounts
  mysql_user:
      name: root
      host: "{{ item }}"
      password: "{{ creds_mysql_root_pwd }}"
  with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost

- name: Install initialization and backup/restore scripts
  template:
    src: "{{ item.name }}.j2"
    dest: "/root/{{ item.realname | default(item.name) }}"
    owner: root
    group: root
    mode: "{{ item.mode | default('0555')}}"
  with_items:
    - { name: backup_mysql.sh }
    - { name: restore_mysql.sh }
    - { name: create_databases.sql }
    - { name: client.cnf, realname: .my.cnf, mode: '0400' }

- name: ensure anonymous users are not in the database
  mysql_user: name='' host={{ item }} state=absent
  with_items:
    - localhost
    - "{{ ansible_hostname }}"

- name: remove the test database
  mysql_db: name=test state=absent

- name: Create databases
  shell: "mysql < /root/create_databases.sql"
