---
- include_vars: /etc/puppet/hiera/sf/sfcreds.yaml

- name: Install sql template
  template:
      src: create_database.sql.j2
      dest: /root/create_databases.sql
      owner: root
      group: root
      mode: 0400

- name: Install my.cnf file
  template:
    src: client.cnf.j2
    dest: /root/.my.cnf
    owner: root
    group: root
    mode: 0400

- include: /etc/ansible/tasks/puppet.yml puppet_statement="include ::sfmysql"

- name: Create databases
  shell: "mysql < /root/create_databases.sql"
