role_actions:
  - install
  - setup
  - update
  - get_logs

nodepool_url: https://git.openstack.org/openstack-infra/nodepool
nodepool_commit: master

jenkins_password: "CHANGE_ME"

jenkins_host: "example.com"
jenkins_api_url: "http://{{ jenkins_host }}:8080/jenkins/"

nodepool_loglevel: INFO
nodepool_root_loglevel: WARNING

nodepool_mysql_host: "mysql.example.com"
nodepool_mysql_port: 3306
nodepool_mysql_db: "nodepool"
nodepool_mysql_user: "nodepool"
nodepool_mysql_password: "CHANGE_ME"
