role_actions:
  - install
  - setup
  - update
  - get_logs

nodepool_url: https://git.openstack.org/openstack-infra/nodepool
nodepool_commit: master

jenkins_host: "jenkins.{{fqdn}}"
jenkins_api_url: "http://{{ jenkins_host }}:8080/jenkins/"
