creds_mysql_root_pwd: MYSQL_ROOT_PWD
creds_redmine_sql_pwd: REDMINE_SQL_PWD
creds_gerrit_sql_pwd: GERRIT_SQL_PWD
creds_nodepool_sql_pwd: NODEPOOL_SQL_PWD
creds_etherpad_sql_pwd: ETHERPAD_SQL_PWD
creds_lodgeit_sql_pwd: LODGEIT_SQL_PWD
creds_grafana_sql_pwd: GRAFANA_SQL_PWD
creds_storyboard_sql_pwd: STORYBOARD_SQL_PWD
creds_storyboard_rabbitmq_password: STORYBOARD_RABBITMQ_PWD
creds_storyboard_service_token: STORYBOARD_SERVICE_TOKEN
creds_cauth_sql_pwd: CAUTH_SQL_PWD
creds_managesf_sql_pwd: MANAGESF_SQL_PWD
creds_issues_tracker_api_key: REDMINE_API_KEY
creds_gerrit_email_pk: GERRIT_EMAIL_PK
creds_gerrit_token_pk: GERRIT_TOKEN_PK
creds_jenkins_pub_key: JENKINS_PUB_KEY
creds_service_pub_key: SERVICE_PUB_KEY
creds_jenkins_user_password: JENKINS_USER_PASSWORD
creds_gerrit_local_sshkey: GERRIT_SERV_PUB_KEY
creds_gerrit_admin_sshkey: GERRIT_ADMIN_PUB_KEY
creds_etherpad_admin_key: ETHERPAD_ADMIN_KEY
creds_lodgeit_session_key: LODGEIT_SESSION_KEY
creds_sf_service_user_pwd: SF_SERVICE_USER_PWD
creds_mumble_ice_secret: MUMBLE_ICE_SECRET
