ssh_keys:
  ssh_root_service:
    user: root
    type: rsa
    key: "%{hiera('creds_service_pub_key')}"
ssh_keys_gerrit:
  ssh_gerrit_jenkins:
    user: gerrit
    type: rsa
    key: "%{hiera('creds_jenkins_pub_key')}"
ssh_keys_jenkins:
  ssh_jenkins_jenkins:
    user: jenkins
    type: rsa
    key: "%{hiera('creds_jenkins_pub_key')}"
