---
- name: Generate random DB password for grafana
  shell: dd if=/dev/urandom bs=1 count=32 2>/dev/null | base64 -w 32 | head -n1
  register: creds_grafana_sql_pwd

- name: Add creds_graphite_sql_pwd to sfcreds.yaml
  lineinfile:
    dest: /etc/puppet/hiera/sf/sfcreds.yaml
    create: yes
    state: present
    regexp: 'creds_grafana_sql_pwd.*'
    line: "creds_grafana_sql_pwd: {{ creds_grafana_sql_pwd.stdout }}"

- name: Generate random Django key for graphite
  shell: dd if=/dev/urandom bs=1 count=32 2>/dev/null | base64 -w 32 | head -n1
  register: creds_graphite_secret_key

- name: Add creds_graphite_sql_pwd to sfcreds.yaml
  lineinfile:
    dest: /etc/puppet/hiera/sf/sfcreds.yaml
    create: yes
    state: present
    regexp: 'creds_graphite_secret_key.*'
    line: "creds_graphite_secret_key: {{ creds_graphite_secret_key.stdout }}"

- name: Generate random DB password for graphite
  shell: dd if=/dev/urandom bs=1 count=32 2>/dev/null | base64 -w 32 | head -n1
  register: creds_graphite_sql_pwd

- name: Add creds_graphite_sql_pwd to sfcreds.yaml
  lineinfile:
    dest: /etc/puppet/hiera/sf/sfcreds.yaml
    create: yes
    state: present
    regexp: 'creds_graphite_sql_pwd.*'
    line: "creds_graphite_sql_pwd: {{ creds_graphite_sql_pwd.stdout }}"

- name: Add user grafana
  user: name=grafana

- name: Add user carbon
  user: name=carbon
