---
# file: roles/all/tasks/main.yml

- name: Backup
  command: echo managesf-cli --host {{ sf_gateway }} --auth {{ sf_username }}:{{ sf_password }} backup

- name: Get new roles
  command: /root/software-factory/fetch_roles.sh trees
  args:
    chdir: /root/software-factory/

- name: Extract roles
  command: /root/software-factory/extract_upstream_roles.sh
  args:
    chdir: /root/software-factory/

- name: Prepare metadata
  command: rsync -av /root/software-factory/edeploy/metadata/ /var/lib/debootstrap/metadata/

- name: Stop puppetserver
  service: name=httpd state=stopped

- name: Stop puppet agent
  service: name=puppet state=stopped

- name: Upgrade install server
  command:  /usr/sbin/edeploy upgrade 0.9.3

