---
- include_vars: /etc/puppet/hiera/sf/sfcreds.yaml
- include_vars: /etc/puppet/hiera/sf/ssh.yaml
- include_vars: /etc/puppet/hiera/sf/_arch.yaml

- name: "system: set /etc/ssh/ssh_known_hosts for all inventory"
  template: 
    src=global_known_hosts.j2 
    dest=/etc/ssh/ssh_known_hosts 
    owner=root group=root mode=0644

- name: "system: chmod ssh directory"
  file: 
    path=/root/.ssh 
    state=directory 
    owner=root group=root mode=0755

# FIXME: I had to use the ":" syntax to be able on add the content
- name: "system: ensure id_rsa private key for root user is present"
  copy:
    content: "{{ service_rsa }}"
    dest: /root/.ssh/id_rsa
    owner: root
    group: root
    mode: 0600

- name: "system: set authorized key to allow config update from jenkins"
  authorized_key:
    user: root
    key: "{{ jenkins_rsa_pub }}"
    key_options: 'command="/usr/local/bin/sf-config-update.sh",no-port-forwarding,no-x11-forwarding,no-agent-forwarding'

- name: "system: set authorized key to allow root access from managesf to other nodes"
  authorized_key:
    user: root
    key: "{{ service_rsa_pub }}"
