---
- include_vars: /etc/puppet/hiera/sf/sfcreds.yaml
- include_vars: main.yml

# mandatory: gerrit user is not present when the playbook is applied
- name: "system: ensure user are present"
  user:
    name: "{{ item.name }}"
    state: present
  with_items: "{{ users }}"

- name: "system: chmod ssh directory for root jenkins and gerrit user"
  file:
    owner: "{{ item.name }}"
    group: "{{ item.group }}"
    path: "{{ item.path }}"
    state: directory
    mode: 0700
  with_items: "{{ users }}"

- name: "system: ensure static directory exist for gerrit"
  file:
    path: "/home/gerrit/site_path/etc"
    owner: gerrit
    group: gerrit
    state: directory
    mode: 0755

- name: "system: ensure ssh key(s) are present for root, jenkins and gerrit users"
  copy:
    owner: "{{ item.0.name }}"
    group: "{{ item.0.name }}"
    content: "{{ item.1.key }}"
    dest: "{{ item.1.filename}}"
    mode: "{{ item.1.mode|default(0600)}}"
  with_subelements:
      - "{{ users }}"
      - ssh_keys
      - flags:
        skip_missing: True

- name: "system: set authorized key for root  gerrit users"
  authorized_key:
    user: "{{ item.0.name }}"
    key: "{{ item.1.key }}"
    key_options: "{{item.1.key_options|default(omit)}}"
  with_subelements:
      - "{{ users }}"
      - authorized_keys
      - flags:
        skip_missing: True
