---
- name: "Create libexec directory"
  file: path=/usr/local/libexec/software-factory state=directory mode=0755

# Install git>2
- name: "git - Remove rpm package"
  command: rpm -e --nodeps git

- name: "git - Fetch git source"
  unarchive: src={{git_url}} dest=/usr/src/ copy=no

- name: "git - Compile and install source"
  command: chdir=/usr/src/git-{{git_version}}/ {{ item }}
  with_items:
    - make configure
    - ./configure --prefix=/usr
    - make all
    - make install

- name: "Install sfmanager venv"
  command: chdir=/usr/src/python-sfmanager {{ item }}
  with_items:
    - virtualenv /srv/sfmanager
    - sed -i 's/^.*pysflib.*//' requirements.txt
    - /srv/sfmanager/bin/pip install --upgrade 'pbr' 'pip'
    - /srv/sfmanager/bin/pip install -rrequirements.txt
    - /srv/sfmanager/bin/python setup.py install --install-scripts /usr/bin

- name: "Install pysflib"
  command: chdir=/usr/src/pysflib {{ item }}
  with_items:
    - /srv/sfmanager/bin/pip install -rrequirements.txt
    - /srv/sfmanager/bin/python setup.py install
