---
- name: "Create libexec directory"
  file: path=/usr/local/libexec/software-factory state=directory mode=0755

- name: "Install sfmanager"
  yum:
    name: "python2-sfmanager"
    state: latest
    disablerepo: "{{ yum_disable_repo|default(omit) }}"
    enablerepo: "{{ yum_enable_repo|default(omit) }}"
