---
- include_vars: /etc/puppet/hiera/sf/sfcreds.yaml
- include_vars: /etc/puppet/hiera/sf/_arch.yaml
- template: src=/etc/ansible/templates/etc-hosts.j2 dest=/etc/hosts mode=0644
- known_hosts: name='[192.168.135.101]:29418' state=absent
- known_hosts: name='[localhost]:29418' state=absent

- name: "Disable root password login"
  user: name=root password="*"

- name: "Set /etc/ssh/ssh_known_hosts for all inventory"
  template: src=global_known_hosts.j2 dest=/etc/ssh/ssh_known_hosts owner=root group=root mode=0644

- name: "Allow apache to connect database"
  seboolean: name={{ item }} state=yes persistent=yes
  with_items: [httpd_can_network_connect, httpd_can_network_connect_db]
  when: selinuxenabled

- name: "puppet: add include statement"
  include: /etc/ansible/tasks/puppet.yml puppet_statement="include ::sfbase, ::postfix"

- name: "rsyslog: configure ommail (mail output module)"
  template: src=mail-ssh-login.j2 dest=/etc/rsyslog.d/mail-ssh-login.conf
  register: rsyslog_config

- name: "syslog: manage service"
  service: name=rsyslog state=restarted
  when: rsyslog_config|changed
