---
- name: Generate random admin password for etherpad
  shell: dd if=/dev/urandom bs=1 count=32 2>/dev/null | base64 -w 32 | head -n1
  register: creds_etherpad_admin_key

- name: Add creds_etherpad_admin_key to sfcreds.yaml
  lineinfile:
    dest: /etc/puppet/hiera/sf/sfcreds.yaml
    create: yes
    state: present
    regexp: 'creds_etherpad_admin_key.*'
    line: "creds_etherpad_admin_key: {{ creds_etherpad_admin_key.stdout }}"
