---
- name: Create upstream cache directory
  file: path={{ upstream_path }} state=directory mode=0755

- name: Fetch SF image
  get_url: url={{ swift_base }}/{{ item }} dest={{ upstream_path }}/{{ item }}
  with_items:
    - softwarefactory-{{ version }}.digest
    - softwarefactory-{{ version }}.img.qcow2

- name: Check digest
  command: chdir={{ upstream_path }} gpg --verify softwarefactory-{{ version }}.digest
  when: gpgcheck == true

- name: Check hash - get
  command: chdir={{ upstream_path }} sha256sum softwarefactory-{{ version }}.img.qcow2
  register: image_hash

- name: Check hash - check
  command: chdir={{ upstream_path }} grep {{ image_hash.stdout }} softwarefactory-{{ version }}.digest

- name: Convert to raw
  command: chdir={{ upstream_path }} qemu-img convert -f qcow2 -O raw softwarefactory-{{ version }}.img.qcow2 softwarefactory-{{ version }}.img.raw

- name: Get startsector
  shell: file {{ upstream_path }}/softwarefactory-{{ version }}.img.raw | sed 's/.*startsector \([^,]*\).*/\1/g'
  register: start_sector

- name: Mount image
  command: mount -n -o loop,offset={{ start_sector.stdout|int * 512 }} {{ upstream_path }}/softwarefactory-{{ version }}.img.raw {{ install_path }}/softwarefactory
