---
- name: Generate random DB password for grafana
  shell: dd if=/dev/urandom bs=1 count=32 2>/dev/null | base64 -w 32 | head -n1
  register: creds_grafana_sql_pwd

- name: Add creds_grafana_sql_pwd to sfcreds.yaml
  lineinfile:
    dest: /etc/puppet/hiera/sf/sfcreds.yaml
    create: yes
    state: present
    regexp: 'creds_grafana_sql_pwd.*'
    line: "creds_grafana_sql_pwd: {{ creds_grafana_sql_pwd.stdout }}"

- name: Generate random DB password for gnocchi
  shell: dd if=/dev/urandom bs=1 count=32 2>/dev/null | base64 -w 32 | head -n1
  register: creds_gnocchi_sql_pwd

- name: Add creds_gnocchi_sql_pwd to sfcreds.yaml
  lineinfile:
    dest: /etc/puppet/hiera/sf/sfcreds.yaml
    create: yes
    state: present
    regexp: 'creds_gnocchi_sql_pwd.*'
    line: "creds_gnocchi_sql_pwd: {{ creds_gnocchi_sql_pwd.stdout }}"

- name: Add user grafana
  user: name=grafana

- name: Add user carbon
  user: name=carbon

- name: Add user gnocchi
  user: name=gnocchi
