---
- name: Check if policy config is already in config-repo
  stat: path=/root/config/policies
  register: configrepo_policies

- name: Check if policy config has job api entries
  when: configrepo_policies.stat.exists == true
  shell: grep 'managesf.job.get' /root/config/policies
  register: grep
  ignore_errors: yes

- name: Include sfconfig.yaml to get fqdn
  include_vars: /etc/puppet/hiera/sf/sfconfig.yaml

- name: Init policy configuration
  when: configrepo_policies.stat.exists == true && not grep.stdout
  command: chdir=/root/config {{ item }}
  with_items:
    - git fetch --all
    - git reset --hard origin/master --
    - git clean -f -x -d
    # Create default rules
    - echo "'managesf.job:get': 'rule:any'" >> policies/policy.yaml
    - echo "'managesf.job.stop: 'rule:admin_or_service'" >> policies/policy.yaml
    - echo "'managesf.job.run': 'rule:admin_or_service'" >> policies/policy.yaml
    - git add policies
    - git commit -m "Initialize job API policies"
    - git push git+ssh://{{ fqdn }}/config master
