---
- name: Check if policy config is already in config-repo
  stat: path=/root/config/policies
  register: configrepo_policies

- name: Include sfconfig.yaml to get fqdn
  include_vars: /etc/puppet/hiera/sf/sfconfig.yaml

- name: Init policy configuration
  when: configrepo_policies.stat.exists == false
  command: chdir=/root/config {{ item }}
  with_items:
    - git fetch --all
    - git reset --hard origin/master --
    - git clean -f -x -d
    - mkdir policies
    - bash -c "cp /var/www/managesf/etc/sf-policy.json /root/config/policies/policy.json || touch /root/config/policies/policy.json"
    - git add policies
    - git commit -m "Initialize policy configuration"
    - git push git+ssh://{{ fqdn }}/config master
