---
- name: Check if /etc/puppet/hiera/sf exist
  stat:
      path: /etc/puppet/hiera/sf
  register: puppet_directory_exist

# During testing, some datas are present
# in /etc/software-factory (arch files),
# we need to sync them  to
# /etc/puppet/hiera/sf not loose data
#- name: Copy data from /etc/software-factory
#  synchronize:
#      src: /etc/software-factory/
#      dest: /etc/puppet/hiera/sf/
#  when:
#      - puppet_directory_exist

- name: Copy data to /etc/software-factory
  synchronize:
      src: /etc/puppet/hiera/sf/
      dest: /etc/software-factory/
  when:
      - puppet_directory_exist

- name: Cleanup puppet directory
  file:
      path: /etc/puppet/hiera/sf
      state: absent
