---
- name: Stop Apache service
  service: name=httpd state=stopped
  when: "'redmine' in roles"

- name: Migrate Redmine DB
  shell: /usr/bin/bundle exec rake db:migrate --trace RAILS_ENV=production chdir=/var/www/redmine
  when: "'redmine' in roles"

- name: Migrate Redmine plugins
  shell: /usr/bin/bundle exec rake redmine:plugins --trace RAILS_ENV=production chdir=/var/www/redmine
  when: "'redmine' in roles"

- name: Clear Redmine cache and sessions
  shell: /usr/bin/bundle exec rake tmp:cache:clear tmp:sessions:clear --trace RAILS_ENV=production chdir=/var/www/redmine
  when: "'redmine' in roles"

- name: Start Apache service
  service: name=httpd state=started
  when: "'redmine' in roles"
