---
- name: Stop Gerrit service
  service: name=gerrit state=stopped

- name: Upgrade Gerrit schema
  shell: /usr/bin/java -jar /home/gerrit/gerrit.war init -d /home/gerrit/site_path --batch --no-auto-start

- name: Ensure old reviewers by blame plugin has been removed
  file: path=/home/gerrit/site_path/plugins/reviewersbyblame-2.8.1.jar state=absent

- name: Create secondary Gerrit index
  shell: /usr/bin/java -jar /home/gerrit/gerrit.war reindex -d /home/gerrit/site_path

- name: Fix Gerrit permissions
  file: path=/home/gerrit/ state=directory recurse=yes owner=gerrit group=gerrit

- name: Start Gerrit service
  service: name=gerrit state=started

- name: Stop Apache service
  service: name=httpd state=stopped

- name: Migrate Redmine DB
  shell: /usr/bin/bundle exec rake db:migrate --trace RAILS_ENV=production chdir=/var/www/redmine

- name: Migrate Redmine plugins
  shell: /usr/bin/bundle exec rake redmine:plugins --trace RAILS_ENV=production chdir=/var/www/redmine

- name: Clear Redmine cache and sessions
  shell: /usr/bin/bundle exec rake tmp:cache:clear tmp:sessions:clear --trace RAILS_ENV=production chdir=/var/www/redmine

- name: Start Apache service
  service: name=httpd state=started
