---
# Stop all service mariadb, gerrit, ...
- name: Stop services
  service: name={{ item }} state=stopped
  ignore_errors: yes
  with_items:
    - monit
    - httpd
    - jenkins
    - zuul
    - zuul-merger
    - nodepool
    - gerrit
    - etherpad
    - lodgeit
    - mariadb
    - gerritbot
    - grafana-server
    - postfix
    - umurmurd
    - log-gearman-client
    - log-gearman-worker
    - elasticsearch
    - logstash
    - kibana
    - storyboard
    - rabbitmq-server
    - storyboard-worker
    - repoxplorer-webui
    - repoxplorer
