---
# Stop all service mariadb, gerrit, ...
- name: Stop services
  service: name={{ item }} state=stopped
  ignore_errors: yes
  with_items:
    - monit
    - httpd
    - jenkins
    - zuul
    - zuul-server
    - gerrit
    - etherpad
    - loedgeit
    - mariadb
    - gerritbot
    - grafana-server
    - postfix
