---
# Stop all service mariadb, gerrit, ...
- name: Stop services
  service: name={{ item }} state=stopped
  ignore_errors: yes
  with_items:
    - monit
    - httpd
    - jenkins
    - zuul
    - zuul-merger
    - nodepool
    - gerrit
    - etherpad
    - lodgeit
    - mariadb
    - gerritbot
    - grafana-server
    - postfix
    - openstack-gnocchi-api
    - openstack-gnocchi-metricd
    - openstack-gnocchi-statsd
    - murmurd
    - log-gearman-client
    - log-gearman-worker
    - elasticsearch
    - logstash
    - storyboard
