---
- include: /etc/ansible/tasks/create_user.yml user_name=joblogsclient

- name: "Create configuration directory"
  file: path=/etc/log-gearman-client/ state=directory mode=0755

- name: "Create log directory"
  file: path=/var/log/log-gearman-client/ state=directory mode=0755 owner=joblogsclient group=joblogsclient

- name: "Install log gearman client configuration"
  template: src=templates/jenkins-log-client.yaml.j2 dest=/etc/log-gearman-client/config.yml owner=joblogsclient group=joblogsclient
  register: config

- name: "Install service file"
  copy:
      src: log-gearman-client.service
      dest: /usr/lib/systemd/system/log-gearman-client.service
      owner: root
      group: root
      mode: 0644

- name: "Start service"
  systemd:
      name: log-gearman-client
      state: started
      daemon_reload: yes
      enabled: yes

- name: "Restart log gearman client if needed"
  service: name=log-gearman-client state=restarted
  when: config|changed
