---
- name: "Install log gearman client configuration"
  template: src=templates/jenkins-log-client.yaml.j2 dest=/etc/log-gearman-client/config.yml owner=joblogsclient group=joblogsclient
  register: config

- name: "Start service"
  systemd:
      name: log-gearman-client
      state: restarted
      daemon_reload: yes
      enabled: yes
