---
- name: "Install log gearman client configuration"
  template: src=templates/jenkins-log-client.yaml.j2 dest=/etc/log-gearman-client/config.yml owner=joblogsclient group=joblogsclient
  register: config
- name: "Enable log gearman client"
  service: name=log-gearman-client enabled=yes state=started
  when: not joblogs_indexation['disabled']
- name: "Disable log gearman client"
  service: name=log-gearman-client enabled=no state=stopped
  when: joblogs_indexation['disabled']
- name: "Restart log gearman client if needed"
  service: name=log-gearman-client state=restarted
  when: config|changed and not joblogs_indexation['disabled']
