---
- name: "Add the kibana RPM repository"
  yum_repository:
    name: kibana
    description: Kibana repository
    baseurl: "{{ kibana_repo_url }}"

- name: "Install kibana package"
  yum:
    name: kibana
    state: latest
