---
- name: Ensure Kibana access to ElasticSearch
  lineinfile: dest=/opt/kibana/config/kibana.yml
              regexp="^elasticsearch.url{{':'}} \"http://elasticsearch.{{ fqdn }}:9200\""
              line="elasticsearch.url{{':'}} \"http://elasticsearch.{{ fqdn }}:9200\""
- name: Kibana service started and enabled
  service: name=kibana state=started enabled=yes
